//=============================================================================
// Generated by RPG Maker.
// Do not edit this file directly.
//=============================================================================

var $plugins = [
  {
    name: "MessageBox",
    status: true,
    description: "A themed message-box plugin.",
    parameters: {
      windowTitle: "Dialogue",
      okButton: "Confirm",
      cancelButton: "Back",
      maxWidth: "816",
      frameColor: "#3355aa",
    },
  },
  {
    name: "NameInput",
    status: true,
    description: "Name entry prompt.",
    parameters: { prompt: "Enter your name", charSet: "ABCDEF", maxChars: "12" },
  },
  {
    name: "QuestLog",
    status: false,
    description: "Quest tracker.",
    parameters: { menuLabel: "Quests", emptyText: "No active quests.", iconIndex: "87" },
  },
  {
    name: "CoreEngine",
    status: true,
    description: "Numeric-only tuning.",
    parameters: { screenWidth: "816", screenHeight: "624" },
  },
];
