export {
  buildConflictIndex,
  generateTerminologyCandidates,
  generateTerminologyCandidatesBatch,
  type GenerateTerminologyCandidatesOptions,
} from "./agent.js";
export {
  buildPrompt,
  canonicalizeUnits,
  PROMPT_TEMPLATE_VERSION_V1,
  promptHash,
  type RenderedPrompt,
} from "./prompt-template.js";
export {
  resolveTerminologyCandidateProvider,
  runCheckTerminologyCandidatesCli,
  runGenerateTerminologyCandidatesCli,
  type CheckTerminologyCandidatesCliInput,
  type GenerateTerminologyCandidatesCliInput,
  type GenerateTerminologyCandidatesCliResult,
  type TerminologyCandidateCliDependencies,
  type CentralTerminologyCheckResult,
} from "./cli.js";
export {
  TERMINOLOGY_CANDIDATE_KINDS,
  TerminologyCandidateEmptyInputError,
  TerminologyCandidateInvalidKindError,
  TerminologyCandidateLocaleMismatchError,
  TerminologyCandidateNotInUnitsError,
  TerminologyCandidateParseError,
  TerminologyCandidateUncitedError,
  TerminologyCandidateUnknownCitationError,
  type BridgeUnitForTerminology,
  type CandidateKind,
  type DeduplicatedTerminologyCandidate,
  type ExistingGlossaryEntry,
  type PriorCandidateRef,
  type ProviderEmittedPack,
  type TerminologyCandidate,
  type TerminologyCandidateInput,
  type TerminologyCandidateInvalidatedReason,
  type TerminologyCandidateModelProfile,
  type TerminologyCandidateOutput,
  type TerminologyCandidateStatus,
} from "./shapes.js";
