export {
  catalogFuzzyCandidateSchemaVersion,
  catalogFuzzyCandidateGeneratorVersion,
  catalogFuzzyCandidateStatusValues,
  type CatalogFuzzyCandidateStatus,
  catalogFuzzyCandidateDiagnosticCodeValues,
  type CatalogFuzzyCandidateDiagnosticCode,
  type CatalogFuzzyCandidateExternalId,
  type CatalogFuzzyCandidateSourceFact,
  type CatalogFuzzyCandidateRequest,
  type CatalogFuzzyCandidateDiagnostic,
  type CatalogFuzzyCandidateResult,
  type ItotoriCatalogFuzzyCandidateGeneratorPort,
  ItotoriCatalogFuzzyCandidateGeneratorService,
} from "./catalog-fuzzy-candidate-generator-01.js";
