export {
  catalogPlatformLanguageConflictSchemaVersion,
  catalogPlatformLanguageConflictReasonCode,
  catalogPlatformLanguageConflictOriginValues,
  type CatalogPlatformLanguageConflictOrigin,
  catalogPlatformLanguageConflictStatusValues,
  type CatalogPlatformLanguageConflictStatus,
  catalogPlatformLanguageConflictDiagnosticCodeValues,
  type CatalogPlatformLanguageConflictDiagnosticCode,
  catalogPlatformLanguageConflictCompatibilityBasisValues,
  type CatalogPlatformLanguageConflictCompatibilityBasis,
  type CatalogPlatformLanguageConflictEvidence,
  type CatalogPlatformLanguageConflictRequest,
  type CatalogPlatformLanguageConflictFact,
  type CatalogPlatformLanguageConflictDiagnostic,
  type CatalogPlatformLanguageConflictResult,
  augmentCatalogPlatformLanguageConflicts,
} from "./catalog-platform-language-conflict-types.js";
