export const API_STRICT_PLAY_BODY_KEYS = {
  ApiLaunchPassResponse: [
    "schemaVersion",
    "outcome",
    "journalRunId",
    "startedAt",
    "refusalMessage",
  ],
  ApiLaunchPassRequest: ["localeBranchId"],
  ApiLocalizationPassControlRequest: [],
  ApiLocalizationPassControlResponse: [
    "schemaVersion",
    "action",
    "journalRunId",
    "status",
    "transitionedAt",
  ],
  ApiPlayRouteMapResponse: [
    "schemaVersion",
    "generatedAt",
    "projectId",
    "localeBranchId",
    "nodes",
    "edges",
    "counts",
  ],
  ApiPlayUnitFeedbackResponse: [
    "schemaVersion",
    "projectId",
    "localeBranchId",
    "bridgeUnitId",
    "notes",
  ],
  ApiPlayAddressableUnitResponse: ["schemaVersion", "projectId", "localeBranchId", "unit"],
  ApiPlayFlagAnnotationResponse: [
    "schemaVersion",
    "projectId",
    "localeBranchId",
    "feedbackReportId",
    "feedbackEvidenceId",
    "severity",
    "category",
    "note",
    "triageLabel",
    "contextStatus",
    "contextCorrectionId",
    "duplicate",
  ],
  ApiPlayTargetEditRequest: ["bridgeUnitId", "targetBody"],
  ApiPlayTargetEditResponse: [
    "schemaVersion",
    "resultRevisionId",
    "patchVersionId",
    "runId",
    "parentPatchVersionId",
    "bridgeUnitId",
    "targetBody",
    "status",
    "selectedAt",
    "idempotentReplay",
  ],
  ApiPlayDeliveryResponse: [
    "schemaVersion",
    "patchVersionId",
    "runId",
    "parentPatchVersionId",
    "status",
    "selectedAt",
    "artifactHashes",
    "downloadUrl",
    "units",
  ],
  ApiPlayDeliveryUnit: ["bridgeUnitId", "unitOrdinal", "targetBody"],
  ApiPatchIterationDeliveryResponse: [
    "schemaVersion",
    "patchVersionId",
    "runId",
    "parentPatchVersionId",
    "origin",
    "status",
    "playableAt",
    "artifactHashes",
    "downloadUrl",
    "units",
  ],
  ApiPatchIterationVersionsResponse: ["schemaVersion", "versions"],
  ApiPatchIterationSurfaceResponse: ["schemaVersion", "patch", "versions", "feedback"],
  ApiPatchIterationPlayRequest: [
    "adapterId",
    "operation",
    "artifactRoot",
    "output",
    "launchDescriptor",
  ],
  ApiPatchIterationPlayResponse: ["schemaVersion", "receipt"],
  ApiPatchIterationFeedbackBatchRequest: ["feedbackBatchId", "label"],
  ApiPatchIterationFeedbackBatchResponse: ["schemaVersion", "batch"],
  ApiPatchIterationFeedbackRequest: [
    "feedbackBatchId",
    "playSessionId",
    "eventKind",
    "body",
    "metadata",
    "targetBody",
    "resultRevisionId",
    "contextArtifactId",
    "contextEntryVersionId",
    "contextFeedback",
    "affectedBridgeUnitIds",
  ],
  ApiPatchIterationFeedbackResponse: ["schemaVersion", "feedback"],
  ApiPatchIterationRefineRequest: [
    "feedbackBatchIds",
    "feedbackEventIds",
    "scopeUnitIds",
    "targetBodiesByUnit",
    "wikiHeads",
  ],
  ApiPatchIterationRefineResponse: ["schemaVersion", "refinement", "patch"],
} as const;
