import {
  CatalogBenchmarkSeedFinderReadModel,
  CatalogCompletenessBenchmarkPools,
  CatalogConflictReviewReadModel,
  CatalogContextPanelReadModel,
  CatalogOpportunityRankingReadModel,
  CostDrilldownPage,
  JobsRunTableReadModel,
  ProjectOverviewReadModel,
  QueueHealthReadModel,
} from "./dependencies.js";
import { ApiErrorResponse } from "./api-domain-01.js";
import {
  ApiAssetDecisionsResponse,
  ApiBenchmarkReportsResponse,
  ApiCandidateAssetsResponse,
  ApiConfigureAuthSsoSettingsRequest,
  ApiModelRoutingModel,
  ApiModelRoutingProvider,
} from "./api-domain-03.js";
import {
  ApiAcceptMemberInvitationRequest,
  ApiAuthBillingSeatUsageResponse,
  ApiAuthCapabilitiesResponse,
  ApiAuthIdentityAccount,
  ApiAuthIdentityResponse,
  ApiAuthSessionRecord,
  ApiAuthSessionsListResponse,
  ApiBranchPolicyGlossaryReference,
  ApiBranchPolicyRule,
  ApiBranchPolicySections,
  ApiBranchPolicySettingsResponse,
  ApiBranchPolicySourceRevisionReference,
  ApiBranchPolicyVersion,
  ApiConfigureAuthSsoSettingsResponse,
  ApiInviteMemberRequest,
  ApiLocalizationRunConfigResponse,
  ApiMemberInvitationResponse,
  ApiMemberRecord,
  ApiMemberResponse,
  ApiMembersListResponse,
  ApiModelRoutingPromptPreset,
  ApiModelRoutingRoute,
  ApiModelRoutingSettingsResponse,
  ApiRemoveMemberRequest,
  ApiRevokeAuthSessionRequest,
  ApiRevokeAuthSessionResponse,
  ApiSaveBranchPolicySettingsRequest,
  ApiSaveLocalizationRunConfigRequest,
  ApiSaveModelRoutingSettingsRequest,
  ApiSaveTranslationScopeSettingsRequest,
  ApiTranslationScopeSettingsResponse,
} from "./api-domain-04.js";
import {
  ApiLaunchPassRequest,
  ApiLaunchPassResponse,
  ApiPatchIterationDeliveryResponse,
  ApiPermissionSetRecord,
  ApiPermissionSetsListResponse,
  ApiPlayAddressableUnitResponse,
  ApiPlayDeliveryResponse,
  ApiPlayDeliveryUnit,
  ApiPlayFlagAnnotationResponse,
  ApiPlayRouteMapResponse,
  ApiPlayTargetEditRequest,
  ApiPlayTargetEditResponse,
  ApiPlayUnitFeedbackResponse,
  ApiPrincipalPermissionSetGrantRequest,
  ApiPrincipalPermissionSetGrantResponse,
  ApiRemoveMemberResponse,
} from "./api-domain-05.js";
import {
  ApiPatchIterationFeedbackBatchRequest,
  ApiPatchIterationFeedbackBatchResponse,
  ApiPatchIterationFeedbackRequest,
  ApiPatchIterationFeedbackResponse,
  ApiPatchIterationPlayRequest,
  ApiPatchIterationPlayResponse,
  ApiPatchIterationRefineRequest,
  ApiPatchIterationRefineResponse,
  ApiPatchIterationSurfaceResponse,
  ApiPatchIterationVersionsResponse,
} from "./api-domain-06.js";
import { API_STRICT_PLAY_BODY_KEYS } from "./api-strict-play-keys.js";

export const STRICT_API_BODY_KEYS = {
  ApiErrorResponse: ["error", "code"],
  ApiAssetDecisionsResponse: ["decisions"],
  ApiCandidateAssetsResponse: ["candidateAssets"],
  ApiWikiObjectListResponse: [
    "schemaVersion",
    "generatedAt",
    "snapshotId",
    "sourceObjects",
    "renderings",
  ],
  ApiWikiObjectShowResponse: [
    "schemaVersion",
    "generatedAt",
    "view",
    "history",
    "dependencyImpact",
  ],
  ApiWikiObjectHistoryResponse: ["schemaVersion", "generatedAt", "view", "history"],
  ApiWikiObjectWriteResponse: [
    "schemaVersion",
    "generatedAt",
    "receipt",
    "history",
    "dependencyImpact",
  ],
  ApiWikiObjectApplyResponse: [
    "schemaVersion",
    "generatedAt",
    "receipt",
    "history",
    "dependencyImpact",
  ],
  CatalogBenchmarkSeedFinderReadModel: ["schemaVersion", "targetLanguage", "generatedAt", "rows"],
  CatalogContextPanelReadModel: [
    "schemaVersion",
    "generatedAt",
    "params",
    "row",
    "releases",
    "projectState",
  ],
  CatalogCompletenessBenchmarkPools: ["targetLanguage", "pools", "publicReport"],
  CatalogConflictReviewReadModel: ["rows"],
  CatalogOpportunityRankingReadModel: [
    "schemaVersion",
    "targetLanguage",
    "generatedAt",
    "weightsVersion",
    "rows",
  ],
  CostDrilldownPage: ["filter", "pagination", "rows"],
  JobsRunTableReadModel: ["schemaVersion", "generatedAt", "filter", "pagination", "rows"],
  ProjectOverviewReadModel: [
    "schemaVersion",
    "generatedAt",
    "projectId",
    "progress",
    "decisions",
    "cost",
    "telemetry",
    "costDrilldown",
    "journal",
    "benchmarkHeadline",
    // ovw-launch-pass-action — whether the CALLER may steer the localization
    // (the `draft.write` steer permission). Sourced server-side so the Overview
    // launch-pass action gates itself off the composed payload it already reads
    // (never a client-fabricated capability). See `composeProjectOverviewReadModel`.
    "canSteer",
  ],
  ApiBenchmarkReportsResponse: ["reports"],
  QueueHealthReadModel: ["schemaVersion", "generatedAt", "outbox", "jobs"],
  ApiModelRoutingProvider: [
    "providerId",
    "providerFamily",
    "endpointFamily",
    "providerName",
    "metadata",
  ],
  ApiModelRoutingModel: ["modelRegistryId", "providerId", "modelId", "capabilities", "pricing"],
  ApiModelRoutingPromptPreset: [
    "promptPresetId",
    "promptTemplateVersion",
    "presetSchemaVersion",
    "promptHash",
    "configSnapshot",
  ],
  ApiModelRoutingRoute: [
    "projectId",
    "taskKind",
    "providerId",
    "modelId",
    "modelRegistryId",
    "fallbackModelIds",
    "promptPresetId",
    "promptTemplateVersion",
    "updatedAt",
  ],
  ApiModelRoutingSettingsResponse: [
    "schemaVersion",
    "projectId",
    "generatedAt",
    "providers",
    "models",
    "promptPresets",
    "routes",
  ],
  ApiBranchPolicyRule: ["ruleId", "guidance"],
  ApiBranchPolicySections: ["tone", "terminology", "honorifics", "formatting", "protectedSpans"],
  ApiBranchPolicySourceRevisionReference: ["sourceRevisionId", "revisionKind", "value"],
  ApiBranchPolicyVersion: [
    "styleGuideVersionId",
    "status",
    "versionSequence",
    "createdAt",
    "updatedAt",
    "approvedAt",
    "policy",
  ],
  ApiBranchPolicyGlossaryReference: [
    "referenceId",
    "versionSequence",
    "styleGuideVersionId",
    "glossaryContentHash",
    "glossaryTermCount",
    "updateReason",
    "createdAt",
  ],
  ApiBranchPolicySettingsResponse: [
    "schemaVersion",
    "projectId",
    "localeBranchId",
    "targetLocale",
    "sourceRevision",
    "latestVersion",
    "approvedVersion",
    "branchReference",
    "policy",
  ],
  ApiTranslationScopeSettingsResponse: [
    "schemaVersion",
    "projectId",
    "localeBranchId",
    "scope",
    "updatedAt",
  ],
  ApiSaveTranslationScopeSettingsRequest: ["projectId", "localeBranchId", "scope"],
  ApiLocalizationRunConfigResponse: [
    "schemaVersion",
    "projectId",
    "localeBranchId",
    "configPath",
    "dataRoot",
    "pairPolicyPath",
    "modelId",
    "providerId",
    "runDir",
    "updatedAt",
  ],
  ApiSaveLocalizationRunConfigRequest: [
    "projectId",
    "localeBranchId",
    "configPath",
    "dataRoot",
    "pairPolicyPath",
    "modelId",
    "providerId",
    "runDir",
  ],
  ApiSaveBranchPolicySettingsRequest: [
    "projectId",
    "localeBranchId",
    "expectedPreviousVersionId",
    "updateReason",
    "policy",
  ],
  ApiSaveModelRoutingSettingsRequest: [
    "projectId",
    "taskKind",
    "providerId",
    "modelId",
    "fallbackModelIds",
    "promptPresetId",
    "promptTemplateVersion",
  ],
  ApiConfigureAuthSsoSettingsRequest: ["accountId", "provider", "security", "sessionPolicy"],
  ApiConfigureAuthSsoSettingsResponse: [
    "schemaVersion",
    "accountId",
    "provider",
    "security",
    "sessionPolicy",
    "updatedAt",
  ],
  ApiInviteMemberRequest: [
    "accountId",
    "email",
    "initialPermissionSetIds",
    "expiresAt",
    "reason",
    "requestId",
  ],
  ApiMemberInvitationResponse: [
    "schemaVersion",
    "invitationId",
    "accountId",
    "email",
    "initialPermissionSetIds",
    "expiresAt",
    "acceptedAt",
    "revokedAt",
    "createdAt",
  ],
  ApiAcceptMemberInvitationRequest: [
    "userId",
    "principalId",
    "displayName",
    "email",
    "externalIdentity",
    "reason",
    "requestId",
  ],
  ApiMemberRecord: [
    "membershipId",
    "accountId",
    "userId",
    "principalId",
    "email",
    "displayName",
    "permissionSetIds",
    "createdAt",
  ],
  ApiMemberResponse: ["schemaVersion", "member"],
  ApiMembersListResponse: ["schemaVersion", "accountId", "members"],
  ApiAuthBillingSeatUsageResponse: [
    "schemaVersion",
    "accountId",
    "planId",
    "planName",
    "billingPeriod",
    "seatLimit",
    "includedSeats",
    "usedSeats",
    "pendingInvitations",
    "availableSeats",
    "overSeatLimit",
    "updatedAt",
  ],
  ApiRemoveMemberRequest: ["reason", "requestId"],
  ApiRemoveMemberResponse: ["schemaVersion", "removedMember"],
  ApiPermissionSetRecord: ["permissionSetId", "accountId", "name", "permissions"],
  ApiPermissionSetsListResponse: ["schemaVersion", "accountId", "permissionSets"],
  ApiPrincipalPermissionSetGrantRequest: ["reason", "requestId"],
  ApiPrincipalPermissionSetGrantResponse: [
    "schemaVersion",
    "principalId",
    "permissionSetId",
    "action",
    "updatedMember",
  ],
  ApiAuthSessionRecord: [
    "sessionId",
    "principalId",
    "createdAt",
    "expiresAt",
    "revokedAt",
    "isActive",
    "deviceLabel",
    "userAgent",
    "ipAddress",
  ],
  ApiAuthSessionsListResponse: ["schemaVersion", "principalId", "sessions"],
  ApiRevokeAuthSessionRequest: ["reason", "requestId"],
  ApiRevokeAuthSessionResponse: ["schemaVersion", "revokedSession"],
  ApiAuthIdentityAccount: [
    "membershipId",
    "accountId",
    "accountSlug",
    "accountName",
    "permissionSetIds",
    "createdAt",
  ],
  ApiAuthIdentityResponse: [
    "schemaVersion",
    "actorUserId",
    "userId",
    "principalId",
    "email",
    "displayName",
    "accounts",
  ],
  // fnd-caps-context — Studio capability permission view wire envelope.
  ApiAuthCapabilitiesResponse: [
    "schemaVersion",
    "actorUserId",
    "canFlag",
    "canSteer",
    "canReveal",
    "denials",
    "denialReasons",
  ],
  ApiStudioCapabilityDenials: ["flag", "steer", "reveal"],
  // ovw-launch-pass-action — the typed launch-pass response envelope. The
  // schemaVersion const pins the wire shape; a renamed / leaked field fails a
  // contract test instead of silently drifting.
  ...API_STRICT_PLAY_BODY_KEYS,
} as const satisfies Readonly<Record<string, readonly string[]>>;
