export { createDatabaseContext, databaseUrlFromEnv, withDatabase } from "./connection.js";
export type { DatabaseContext, ItotoriDatabase } from "./connection.js";
export * from "./explicit-failure.js";
export {
  AuthorizationError,
  allPermissions,
  applyMappedProviderClaimGrants,
  bootstrapDefaultAccountPrincipal,
  bootstrapLocalUser,
  defaultLocalAccountId,
  defaultLocalAccountName,
  defaultLocalAccountSlug,
  defaultPermissionSetId,
  defaultPermissionSetSeeds,
  localOperatorAllPermissionsSetId,
  localOperatorAllPermissionsSetKey,
  localOperatorAllPermissionsSetName,
  localOperatorDisplayName,
  localOperatorMembershipId,
  localOperatorPrincipalId,
  localOperatorUserId,
  localUserDisplayName,
  localUserId,
  permissionValues,
  ProviderClaimQuarantineError,
  quarantineExternalIdentityProviderClaims,
  requirePermission,
  resolvePrincipalEffectivePermissions,
  seedDefaultPermissionSets,
} from "./authorization.js";
export type {
  AuthorizationActor,
  ExternalIdentityProviderClaim,
  Permission,
} from "./authorization.js";
export { llmContentReadPermission, permissionBasedLlmContentRead } from "./llm-content-access.js";
export type { LlmContentReadAuthorizer, LlmContentReadRequest } from "./llm-content-access.js";
export {
  assertLlmSha256,
  canonicalLlmJson,
  canonicalParentIds,
  conversationEventId,
  conversationEventIdFromContentHash,
  llmSha256,
  parseLlmJson,
} from "./llm-content-address.js";
export type {
  ConversationEventContentHashIdentityInput,
  ConversationEventIdentityInput,
  LlmJsonValue,
} from "./llm-content-address.js";
export { migrate, resetDatabase } from "./migrations.js";
export {
  BENCHMARK_MANAGED_ARTIFACT_KINDS,
  CORPUS_SIDECAR_ARTIFACT_KINDS,
  MANAGED_ARTIFACT_URI_ROOTS,
  assertManagedArtifactUri,
  benchmarkManagedArtifactRef,
  benchmarkManagedArtifactUri,
  corpusSidecarArtifactRef,
  corpusSidecarManagedArtifactUri,
  managedArtifactCleanupScopePrefix,
  planManagedArtifactCleanup,
  redactPrivateLocalManagedArtifactRef,
} from "./managed-artifact-refs.js";
export {
  ArtifactAuthorizationError,
  ArtifactIdentityCollisionError,
  ArtifactStoreIntegrityError,
  artifactIdForBytes,
  immutableArtifactSnapshotVersion,
} from "./immutable-artifact-store.js";
export type {
  ArtifactAuditAction,
  ArtifactAuditEvent,
  ArtifactAuditOutcome,
  ArtifactDescriptor,
  ArtifactPruneDecision,
  ArtifactPruneReceipt,
  ArtifactReference,
  ArtifactRetentionBasis,
  ArtifactRetentionPolicy,
  ArtifactSnapshotExport,
  ImmutableArtifactSnapshot,
} from "./immutable-artifact-store.js";
export {
  ArtifactRepositoryConflictError,
  openLocalImmutableArtifactRepository,
} from "./immutable-artifact-repository.js";
export type { ImmutableArtifactRepository } from "./immutable-artifact-repository.js";
export {
  DatabaseImmutableArtifactRepository,
  openDatabaseImmutableArtifactRepository,
} from "./immutable-artifact-database-repository.js";
export { ItotoriImmutableArtifactRetentionRepository } from "./immutable-artifact-retention-repository.js";
export type { ImmutableArtifactRetentionReport } from "./immutable-artifact-retention-repository.js";
export type {
  BenchmarkManagedArtifactKind,
  BenchmarkManagedArtifactRef,
  CorpusSidecarArtifactKind,
  CorpusSidecarArtifactRef,
  ManagedArtifactClass,
  ManagedArtifactCleanupCandidate,
  ManagedArtifactCleanupClassification,
  ManagedArtifactCleanupDecision,
  ManagedArtifactCleanupPlan,
  ManagedArtifactCleanupScope,
} from "./managed-artifact-refs.js";
export {
  jobEventTypeValues,
  jobIdempotencyPolicyValues,
  jobStatusValues,
  jobTaskTypeValues,
  outboxEventTypeValues,
  outboxStatusValues,
  providerCostKindValues,
  authProviderClaimKindValues,
  authBillingPeriodValues,
  authSsoProviderProtocolValues,
  providerRunStatusValues,
  projectRunProgressStatusValues,
  projectRunStatusValues,
  runtimeBridgeUnitRefRoleValues,
  runtimeEvidenceKindValues,
  runtimeRunStatusValues,
  styleGuideVersionStatusValues,
  catalogCandidateMatchStatusValues,
  catalogConfidenceValues,
  catalogConflictKindValues,
  catalogConflictStatusValues,
  catalogConflictSubjectKindValues,
  catalogCrawlerJobStatusValues,
  catalogCrawlerStepStatusValues,
  catalogDemandFactKindValues,
  catalogEngineSourceValues,
  catalogExternalIdKindValues,
  catalogInstallStateValues,
  catalogLanguageStatusScopeValues,
  catalogLanguageStatusValues,
  catalogPathRedactionClassValues,
  catalogRawContentRedactionClassValues,
  catalogReleaseKindValues,
  catalogReleaseMappingKindValues,
  catalogReleasePackageKindValues,
  catalogSeedOriginValues,
  catalogSeedStatusValues,
  catalogSourceRecordKindValues,
  catalogSourceValues,
  catalogTranslationPortabilityValues,
  engineCapabilityEvidenceKindValues,
  engineCapabilityEvidenceSourceValues,
  engineCapabilityEvidenceStatusValues,
  exactSearchSourceArtifactTypeValues,
  translationMemoryMatchKindValues,
  translationMemoryReuseStatusValues,
  translationMemorySegmentStatusValues,
  terminologyAliasKindValues,
  terminologyConflictKindValues,
  terminologyConflictStatusValues,
  terminologySemanticIndexStatusValues,
  terminologySourceReferenceKindValues,
  terminologyTermKindValues,
  terminologyTermStatusValues,
  wikiBrandContextRoleValues,
  localizationRunPatchVersionStatusValues,
  localizationPatchVersionOriginValues,
  localizationPatchVersionMemberOriginValues,
  playTestFeedbackBatchSelectionKindValues,
  playTestFeedbackEventKindValues,
} from "./schema.js";
export type {
  AuthSsoProviderProtocol,
  CatalogConfidence,
  CatalogConflictKind,
  CatalogConflictStatus,
  CatalogConflictSubjectKind,
  CatalogCrawlerJobStatus,
  CatalogCrawlerStepStatus,
  CatalogDemandFactKind,
  CatalogEngineSource,
  CatalogExternalIdKind,
  CatalogInstallState,
  CatalogLanguageStatus,
  CatalogLanguageStatusScope,
  CatalogPathRedactionClass,
  CatalogRawContentRedactionClass,
  CatalogReleaseKind,
  CatalogReleaseMappingKind,
  CatalogReleasePackageKind,
  CatalogSeedOrigin,
  CatalogSeedStatus,
  CatalogSource,
  CatalogSourceRecordKind,
  CatalogTranslationPortability,
  EngineCapabilityEvidenceKind,
  EngineCapabilityEvidenceSource,
  EngineCapabilityEvidenceStatus,
  ExactSearchSourceArtifactType,
  TranslationMemoryMatchKind,
  TranslationMemoryReuseStatus,
  TranslationMemorySegmentStatus,
  JobEventType,
  JobIdempotencyPolicy,
  JobStatus,
  JobTaskType,
  OutboxEventType,
  OutboxStatus,
  ProviderCostKind,
  AuthProviderClaimKind,
  ProviderRunStatus,
  ProjectRunProgressStatus,
  ProjectRunStatus,
  RuntimeBridgeUnitRefRole,
  RuntimeEvidenceKind,
  RuntimeRunStatus,
  StyleGuideVersionStatus,
  CatalogCandidateMatchStatus,
  TerminologyAliasKind,
  TerminologyConflictKind,
  TerminologyConflictStatus,
  TerminologySemanticIndexStatus,
  TerminologySourceReferenceKind,
  TerminologyTermKind,
  TerminologyTermStatus,
  WikiBrandContextRole,
  AuthBillingPeriod,
  LocalizationRunPatchVersionStatus,
  LocalizationPatchVersionOrigin,
  LocalizationPatchVersionMemberOrigin,
  PlayTestFeedbackBatchSelectionKind,
  PlayTestFeedbackEventKind,
} from "./schema.js";
export {
  ItotoriAuthBillingSeatRepository,
  ItotoriAuthBillingSeatRepositoryError,
} from "./repositories/auth-billing-seat-repository.js";
export type { AuthAccountSeatUsageRecord } from "./repositories/auth-billing-seat-repository.js";
export {
  defaultWorkspaceId,
  defaultWorkspaceName,
  assertProjectEngineBinding,
  ItotoriProjectRepository,
  ProjectScopeNotFoundError,
  RuntimeRunNotFoundError,
  UnknownProjectEngineFamilyError,
} from "./repositories/project-repository.js";
export type {
  ArtifactInput,
  BenchmarkArtifactLedgerInput,
  BenchmarkQaAgentSummary,
  BenchmarkReportSummary,
  BridgeImportDiffCounts,
  BridgeImportFutureReferences,
  BridgeImportRevisionDiffCounts,
  BridgeImportStatus,
  DashboardDecisionCounts,
  DashboardDecisionReadModel,
  DashboardPendingDecision,
  DashboardPendingDecisionKind,
  EventInput,
  FindingInput,
  ItotoriProjectRecord,
  ItotoriProjectRepositoryPort,
  LoadLocaleBranchDraftTextsInput,
  LocaleBranchIdentity,
  LocaleBranchStatus,
  LocalizationRunProjectScope,
  ProjectDashboardStatus,
  ProjectEngineBinding,
  ProjectEngineFamilyRegistry,
  ProjectExtractProfile,
  RuntimeArtifactHashProvenance,
  RuntimeDashboardArtifact,
  RuntimeDashboardStatus,
} from "./repositories/project-repository.js";
export { RUNTIME_ARTIFACT_HASH_PROVENANCES } from "./repositories/project-repository.js";
export {
  ItotoriJobsRunTableRepository,
  JOBS_RUN_TABLE_DEFAULT_LIMIT,
  JOBS_RUN_TABLE_MAX_LIMIT,
  JOBS_RUN_TABLE_SCHEMA_VERSION,
} from "./repositories/jobs-run-table-repository.js";
export type {
  JobsRunTableCost,
  JobsRunTableFallback,
  JobsRunTableReadModel,
  JobsRunTableRow,
  JobsRunTableTokens,
  JobsRunTableZdr,
  LoadJobsRunTableOptions,
} from "./repositories/jobs-run-table-repository.js";
export {
  ItotoriModelLedgerRepository,
  sanitizeAdapterMetadata,
  COST_DRILLDOWN_DEFAULT_LIMIT,
  COST_DRILLDOWN_MAX_LIMIT,
} from "./repositories/model-ledger-repository.js";
export type {
  CostDrilldownAppliedFilter,
  CostDrilldownFilter,
  CostDrilldownPage,
  CostDrilldownPagination,
  CostDrilldownProviderMetadata,
  CostDrilldownRow,
  CostDrilldownRowCost,
  CostKindBreakdown,
  ItotoriModelLedgerRepositoryPort,
  LedgerJsonRecord,
  ProjectCostReport,
  ProjectTelemetryTimeseries,
  ProjectTelemetryTimeseriesBucket,
  PromptPresetLedgerInput,
  ProviderRunCostSummary,
  ProviderRunLedgerInput,
  ProviderRunZdrCountRow,
  ProviderRunZdrCountWindow,
  TranslationMemoryReuseCostReport,
  TranslationMemoryReuseCostSummary,
} from "./repositories/model-ledger-repository.js";
export {
  ItotoriModelRoutingSettingsRepository,
  ItotoriModelRoutingSettingsRepositoryError,
} from "./repositories/model-routing-settings-repository.js";
export type {
  ItotoriModelRoutingSettingsRepositoryPort,
  ModelRoutingModelRecord,
  ModelRoutingPromptPresetRecord,
  ModelRoutingProviderRecord,
  ModelRoutingRouteRecord,
  ModelRoutingSettingsRecord,
  SaveModelRoutingSettingsInput,
} from "./repositories/model-routing-settings-repository.js";
export {
  DEFAULT_TRANSLATION_SCOPE,
  ItotoriTranslationScopeSettingsRepository,
  ItotoriTranslationScopeSettingsRepositoryError,
  translationScopeValues,
} from "./repositories/translation-scope-settings-repository.js";
export type {
  ItotoriTranslationScopeSettingsRepositoryPort,
  SaveTranslationScopeSettingsInput,
  TranslationScopeSettingsRecord,
  TranslationScopeSettingValue,
} from "./repositories/translation-scope-settings-repository.js";
export {
  ItotoriLocalizationPassRunConfigRepository,
  ItotoriLocalizationPassRunConfigRepositoryError,
} from "./repositories/localization-pass-run-config-repository.js";
export type {
  ItotoriLocalizationPassRunConfigRepositoryPort,
  LocalizationPassRunConfigRecord,
  SaveLocalizationPassRunConfigInput,
} from "./repositories/localization-pass-run-config-repository.js";
export {
  ItotoriProjectRunCostCapError,
  ItotoriProjectRunRepository,
  ItotoriProjectRunRepositoryError,
} from "./repositories/project-run-repository.js";
export { PROJECT_RUN_LIVE_READ_MODEL_SCHEMA_VERSION } from "./repositories/project-run-repository-types.js";
export {
  listProjectRunDashboardRuns,
  listProjectRunPortfolioProgress,
  loadProjectRunLiveReadModel,
} from "./repositories/project-run-repository-read-model.js";
export type {
  AcquireProjectRunLeaseInput,
  AdvanceProjectRunInput,
  CreateProjectRunInput,
  ItotoriProjectRunRepositoryPort,
  ProjectRunCostAccountRecord,
  ProjectRunCostReservationRecord,
  ProjectRunBlockerPage,
  ProjectRunDashboardPage,
  ProjectRunDashboardRow,
  ProjectRunLease,
  ProjectRunLeaseFence,
  ProjectRunLiveReadModel,
  ProjectRunLiveReadModelOptions,
  ProjectRunPortfolioBlocker,
  ProjectRunPortfolioProgressSummary,
  ProjectRunProgressPage,
  ProjectRunProgressRecord,
  ProjectRunProgressStatusCounts,
  ProjectRunRecord,
  ProjectRunStatusCounts,
  RecordProjectRunProgressInput,
  RecordProjectRunProgressBatchInput,
  RenewProjectRunLeaseInput,
  ReserveProjectRunCostInput,
  SettleProjectRunCostInput,
} from "./repositories/project-run-repository-types.js";
export {
  deriveFeedbackDedupeKey,
  feedbackContextStatusValues,
  feedbackReportStatusValues,
  feedbackSourceKindValues,
  feedbackTriageLabelValues,
  feedbackTypeValues,
  ItotoriFeedbackRepository,
  parseManualFeedbackImportInput,
} from "./repositories/feedback-repository.js";
export type {
  FeedbackContextStatus,
  FeedbackReporter,
  FeedbackReportStatus,
  FeedbackSourceKind,
  FeedbackTriageLabel,
  FeedbackType,
  ItotoriFeedbackRepositoryPort,
  ManualFeedbackAttachment,
  ManualFeedbackContextAttachment,
  ManualFeedbackImportInput,
  ManualFeedbackImportResult,
  ManualFeedbackLineReference,
  ManualFeedbackCorrectionContext,
  ManualFeedbackRuntimeArtifactAttachment,
  ManualFeedbackSaveContextAttachment,
  ManualFeedbackScreenshotAttachment,
  ManualFeedbackSourceInput,
  UnitBoundFeedbackNote,
} from "./repositories/feedback-repository.js";
export {
  CHANNEL_PII_KINDS,
  ChannelImportError,
  COMMUNITY_FORMS_CHANNEL,
  CommunityFormsImporter,
  GITHUB_ISSUES_CHANNEL,
  GitHubIssuesImporter,
  redactChannelPii,
} from "./channel-feedback/index.js";
