export {
  AssetLocalizationDecisionRepositoryError,
  AuthorizationError,
  explicitFailurePublicMessage,
  ProjectScopeNotFoundError,
  RuntimeRunNotFoundError,
  assetLocalizationDecisionAssetKindList,
  capabilityLevelValues,
  catalogCandidateMatchStatusValues,
  catalogCompletenessPoolValues,
  catalogConflictStatusValues,
  catalogLanguageStatusValues,
  catalogSourceValues,
  type CapabilityLevel,
  type AssetDecisionRecord,
  type AssetLocalizationDecisionAssetKind,
  type CandidateAssetRecord,
  type CatalogBenchmarkDemandBucket,
  type CatalogBenchmarkLocalOwnership,
  type CatalogBenchmarkSeedFinderFilter,
  type CatalogBenchmarkSeedFinderReadModel,
  type CatalogContextPanelCatalogReadModel,
  type CatalogOpportunityRankingFilter,
  type CatalogOpportunityRankingReadModel,
  permissionValues,
  type CatalogCompletenessBenchmarkPools,
  type CatalogCompletenessPool,
  type CatalogCompletenessPoolFilter,
  type CatalogConflictReviewFilter,
  type CatalogConflictReviewReadModel,
  type CatalogConflictReviewSeverity,
  type CatalogConflictReviewStatus,
  type CatalogLanguageStatus,
  type CatalogSource,
  type CostDrilldownFilter,
  type CostDrilldownPage,
  type DashboardDecisionReadModel,
  type ModelRoutingSettingsRecord,
  type Permission,
  type ProjectCostReport,
  type ProjectDashboardStatus,
  type ProjectTelemetryTimeseries,
  type QueueHealthReadModel,
  type AuthSessionAdminRecord,
  type AuthAccountSeatUsageRecord,
  type LoadQueueHealthOptions,
  type ActorIdentityRecord,
  type MemberInvitationRecord,
  type MemberRecord,
  type PermissionSetRecord,
  type RuntimeDashboardStatus,
  type SaveModelRoutingSettingsInput,
  type TerminologySearchInput,
  type TerminologySearchReadModel,
} from "@itotori/db";
export {
  classifyApplicationFailure as classifyExplicitFailure,
  hasApplicationFailureEvidence as hasExplicitFailureEvidence,
} from "./explicit-failure/index.js";
export { assertBridgeBundleV02, type BridgeBundleV02 } from "@itotori/localization-bridge-schema";
export { resolveStudioCapabilityPermissionView, type ItotoriAuthorizationPort } from "./auth.js";
export { databaseUnreachableMessage } from "./database-unreachable.js";
export {
  ApiValidationError,
  REDACTED_RUNTIME_FINDING_MESSAGE,
  assertItotoriApiResponse,
  assertRedactedRuntimeDashboardStatus,
  parseDraftBranchRequest,
  parseProjectImportRequest,
  parseProjectDecodeExtractRequest,
  parseRecordBenchmarkRequest,
  parseRecordFindingRequest,
  parseRuntimeEvidenceRequest,
  parseSaveBranchPolicySettingsRequest,
  parseSaveLocalizationRunConfigRequest,
  parseSaveModelRoutingSettingsRequest,
  parseSaveTranslationScopeSettingsRequest,
  parseConfigureAuthSsoSettingsRequest,
  parseAcceptMemberInvitationRequest,
  parseInviteMemberRequest,
  parseRemoveMemberRequest,
  parsePrincipalPermissionSetGrantRequest,
  parseRevokeAuthSessionRequest,
  parseLaunchPassRequest,
  parseLocalizationPassControlRequest,
  parsePlayFlagAnnotationRequest,
  parsePlayTargetEditRequest,
  parsePatchIterationPlayRequest,
  parseWikiApplyRequest,
  parseWikiWriteRequest,
  type ApiAuthCapabilitiesResponse,
  type ApiAuthBillingSeatUsageResponse,
  type ApiAuthIdentityResponse,
  type ApiDraftBranchResponse,
  type ApiErrorResponse,
  type ApiLaunchPassResponse,
  type ApiLocalizationPassControlResponse,
  type ApiLocalizationRunConfigResponse,
  type ApiSaveLocalizationRunConfigRequest,
  type ApiPlayRouteMapResponse,
  type ApiPlayFlagAnnotationResponse,
  type ApiPlayUnitFeedbackResponse,
  type ApiPlayAddressableUnitResponse,
  type ApiPlayTargetEditResponse,
  type ApiPlayDeliveryResponse,
  type ApiPatchIterationDeliveryResponse,
  type ApiPatchIterationFeedbackBatchResponse,
  type ApiPatchIterationFeedbackResponse,
  type ApiPatchIterationPlayResponse,
  type ApiPatchIterationRefineResponse,
  type ApiPatchIterationSurfaceResponse,
  type ApiPatchIterationVersionsResponse,
  type JobsRunTableReadModel,
  type LoadJobsRunTableOptions,
  type ApiConfigureAuthSsoSettingsRequest,
  type ApiConfigureAuthSsoSettingsResponse,
  type ApiAcceptMemberInvitationRequest,
  type ApiAssetDecisionsResponse,
  type ApiCatalogContextPanelResponse,
  type ApiBenchmarkReportsResponse,
  type ApiCandidateAssetsResponse,
  type ApiInviteMemberRequest,
  type ApiProjectOverviewResponse,
  type ApiProjectImportResponse,
  type ApiProjectDecodeExtractResponse,
  type ApiProjectsResponse,
  type ApiJobsRunTableResponse,
  type ApiQueueHealthResponse,
  type ApiMemberInvitationResponse,
  type ApiMemberRecord,
  type ApiMemberResponse,
  type ApiMembersListResponse,
  type ApiPermissionSetRecord,
  type ApiPermissionSetsListResponse,
  type ApiPrincipalPermissionSetGrantRequest,
  type ApiPrincipalPermissionSetGrantResponse,
  type ApiRemoveMemberRequest,
  type ApiRemoveMemberResponse,
  type ApiAuthSessionRecord,
  type ApiAuthSessionsListResponse,
  type ApiRevokeAuthSessionRequest,
  type ApiRevokeAuthSessionResponse,
  type ApiModelRoutingSettingsResponse,
  type ApiBranchPolicySettingsResponse,
  type ApiSaveBranchPolicySettingsRequest,
  type ApiTranslationScopeSettingsResponse,
  type ApiSaveTranslationScopeSettingsRequest,
  type ApiWikiEditResponse,
  type ApiWikiApplyResponse,
  type ApiWikiFeedbackResponse,
  type ApiWikiHistoryResponse,
  type ApiWikiListResponse,
  type ApiWikiShowResponse,
  type ItotoriApiResponseBody,
  type ItotoriApiRouteId,
} from "./api-schema.js";
export type { RouteMapReadModelPort } from "./play/route-map-read-model.js";
export type {
  PlayTesterTargetEditResponse,
  PlayablePatchExportResponse,
  SelectedPatchExportResponse,
} from "./play/result-revision-service.js";
export type { DeliveredPatchArchive } from "./patch-export/delivery-archive.js";
export type { BoundPatchbackProduceServicePort } from "./play/patchback-produce-service.js";
export { playDeliveryArchivePath } from "./api-routes.js";
export { buildPlayFlagFeedbackInput, type PlayFlagSeverity } from "./play/flag-annotation.js";
export type { ManualFeedbackImportPort } from "./manual-feedback.js";
export {
  redactProjectOverviewReadModel,
  type ProjectOverviewReadModelOptions,
} from "./project-overview-read-model.js";
export type {
  BenchmarkRecordResult,
  FindingRecordResult,
  ItotoriProjectWorkflowPort,
  LaunchLocalizationPassResult,
  LocalizationPassControlResult,
  RuntimeIngestResult,
} from "./services/project-operations-port.js";
export {
  ProjectMutationScopeError,
  requireOwnedBranchScope,
  resolveProjectMutationScope,
} from "./services/project-mutation-scope.js";
export { configuredServicePort } from "./services/configured-port.js";
export {
  parseAuthBillingSeatUsageQuery,
  parseAuthMembersListQuery,
  parseAuthPermissionSetsListQuery,
  parseCostDrilldownFilter,
  parseJobsRunTableQuery,
  parseModelRoutingSettingsQuery,
  parseProjectOverviewFilter,
  parseProjectScopeQuery,
} from "./api-handler-core-parsers.js";
export {
  decodeApiPathSegment,
  nonEmptySearchParam,
  parseAssetDecisionApiRoute,
  parseAuthMemberAcceptRoute,
  parseAuthMemberRemoveRoute,
  parseAuthPermissionSetGrantRoute,
  parseAuthPermissionSetRevokeRoute,
  parseAuthSessionRevokeRoute,
  parseAuthSessionsRoute,
  parseBranchPolicySettingsApiRoute,
  parseCatalogContextPanelApiRoute,
  parseLocalizationRunConfigApiRoute,
  parseLocalizationPassControlApiRoute,
  parsePatchIterationApiRoute,
  parsePlayAddressableUnitApiRoute,
  parsePlayDeliveryApiRoute,
  parsePlayFlagApiRoute,
  parsePlayRouteMapApiRoute,
  parsePlayTargetEditApiRoute,
  parsePlayUnitFeedbackApiRoute,
  parseTranslationScopeSettingsApiRoute,
  parseWikiObjectApiRoute,
} from "./api-handler-path-parsers.js";
export {
  parseAssetDecisionReadFilter,
  parseCatalogBenchmarkSeedFinderFilter,
  parseCatalogCompletenessPoolFilter,
  parseCatalogConflictReviewFilter,
  parseCatalogOpportunityRankingFilter,
  parseRuntimeRunIdQuery,
  parseTerminologySearchInput,
  parseWikiObjectSnapshotQuery,
} from "./api-handler-catalog-parsers.js";
export {
  authBillingSeatUsageResponseBody,
  authSessionRecordBody,
  authSsoSettingsResponseBody,
  launchPassResponseBody,
  localizationPassControlResponseBody,
  memberInvitationResponseBody,
  memberRecordBody,
  memberResponseBody,
  modelRoutingSettingsResponseBody,
  patchIterationPlayReceiptResponseBody,
  permissionSetRecordBody,
  permissionSetsListResponseBody,
  playDeliveryResponseBody,
  playTargetEditResponseBody,
  principalPermissionSetGrantResponseBody,
  removeMemberResponseBody,
  wikiObjectApplyResponseBody,
  wikiObjectWriteResponseBody,
} from "./api-handler-response-bodies.js";
export type { CatalogContextPanelReadModel } from "./catalog-context-panel.js";
// The kept localize/draft, wiki write, and patch-play mutations route ONLY through
// these thin new-pipeline handlers. Each has a clean transitive import closure (no
// edge to the legacy service graph — proven by composition-reachability); the live
// substrate they drive is injected through the ports on ItotoriApiServices, never
// imported here on their behalf.
export { runApiLocalize } from "./api/localize-route.js";
export { runApiWiki } from "./api/wiki-route.js";
export { runApiPlay } from "./api/play-route.js";
export type {
  LocalizationPerRunInput,
  LocalizationPortSource,
} from "./composition/localize-entrypoint.js";
export type { LocalizationProviderBudgetCohorts } from "./composition/provider-budget-cohort.js";
export type { PlayEntrypointDeps } from "./composition/play-entrypoint.js";
export type { PatchRuntimeLaunchReceipt } from "./play/patch-runtime-launcher.js";
export type { RunPolicyRequest } from "./run-policy/index.js";
export {
  ForgedWikiAssertionError,
  WikiObjectApiError,
  type DecodedFact,
  type EnhancementRunner,
  type WikiObjectApiService,
  type WikiObjectSelector,
  type WikiApplyReceipt,
  type WikiHistoryEntry,
  type WikiWriteReceipt,
} from "./wiki/object-api/index.js";
export type { RunModeValue } from "./contracts/index.js";
export type { OutputScope } from "./run-policy/index.js";
export type { ContextScopeValue } from "./contracts/index.js";
