import type { ItotoriApiRoute } from "./api-routes.js";
import type { ItotoriApiRouteId } from "./api-schema.js";

export const apiRoutesFirst = {
  "projects.list": {
    method: "GET",
    pathTemplate: "/api/projects",
    operationId: "projectsList",
    summary: "List projects with dashboard status.",
    pathParams: [],
    responseSchema: "ApiProjectsResponse",
  },
  "projects.status": {
    method: "GET",
    pathTemplate: "/api/projects/status",
    operationId: "projectsStatus",
    summary: "Project dashboard status.",
    pathParams: [],
    responseSchema: "ProjectDashboardStatus",
  },
  "projects.overview": {
    method: "GET",
    pathTemplate: "/api/projects/overview",
    operationId: "projectsOverview",
    summary: "Composed project overview cockpit read model.",
    pathParams: [],
    responseSchema: "ProjectOverviewReadModel",
  },
  "projects.decisions": {
    method: "GET",
    pathTemplate: "/api/projects/decisions",
    operationId: "projectsDecisions",
    summary: "Dashboard decision read model.",
    pathParams: [],
    responseSchema: "DashboardDecisionReadModel",
  },
  "projects.cost": {
    method: "GET",
    pathTemplate: "/api/projects/cost",
    operationId: "projectsCost",
    summary: "Project cost report.",
    pathParams: [],
    responseSchema: "ProjectCostReport",
  },
  "projects.costDrilldown": {
    method: "GET",
    pathTemplate: "/api/projects/cost/drilldown",
    operationId: "projectsCostDrilldown",
    summary: "Paged cost drill-down.",
    pathParams: [],
    responseSchema: "CostDrilldownPage",
  },
  "projects.benchmarks": {
    method: "GET",
    pathTemplate: "/api/projects/benchmarks",
    operationId: "projectsBenchmarks",
    summary: "Benchmark report summaries.",
    pathParams: [],
    responseSchema: "ApiBenchmarkReportsResponse",
  },
  "jobs.runTable": {
    method: "GET",
    pathTemplate: "/api/jobs/run-table",
    operationId: "jobsRunTable",
    summary: "Paged jobs run table with physical journal attempts and served provider facts.",
    pathParams: [],
    responseSchema: "JobsRunTableReadModel",
  },
  "runtime.status": {
    method: "GET",
    pathTemplate: "/api/runtime/v0.2/status",
    operationId: "runtimeStatus",
    summary: "Runtime dashboard status.",
    pathParams: [],
    responseSchema: "RuntimeDashboardStatus",
  },
  "catalog.conflicts": {
    method: "GET",
    pathTemplate: "/api/catalog/conflicts",
    operationId: "catalogConflicts",
    summary: "Catalog conflict review read model.",
    pathParams: [],
    responseSchema: "CatalogConflictReviewReadModel",
  },
  "catalog.completeness": {
    method: "GET",
    pathTemplate: "/api/catalog/completeness",
    operationId: "catalogCompleteness",
    summary: "Catalog completeness benchmark pools.",
    pathParams: [],
    responseSchema: "CatalogCompletenessBenchmarkPools",
  },
  "catalog.benchmarkSeeds": {
    method: "GET",
    pathTemplate: "/api/catalog/benchmark-seeds",
    operationId: "catalogBenchmarkSeeds",
    summary: "Catalog benchmark seed finder read model.",
    pathParams: [],
    responseSchema: "CatalogBenchmarkSeedFinderReadModel",
  },
  "catalog.contextPanel": {
    method: "GET",
    pathTemplate:
      "/api/projects/{projectId}/locale-branches/{localeBranchId}/catalog-context/{workId}",
    operationId: "catalogContextPanel",
    summary: "Catalog context panel read model for a work and target locale branch.",
    pathParams: ["projectId", "localeBranchId", "workId"],
    responseSchema: "CatalogContextPanelReadModel",
  },
  "catalog.opportunities": {
    method: "GET",
    pathTemplate: "/api/catalog/opportunities",
    operationId: "catalogOpportunities",
    summary: "Catalog opportunity ranking read model.",
    pathParams: [],
    responseSchema: "CatalogOpportunityRankingReadModel",
  },
  "terminology.search": {
    method: "GET",
    pathTemplate: "/api/terminology/search",
    operationId: "terminologySearch",
    summary: "Terminology search read model.",
    pathParams: [],
    responseSchema: "TerminologySearchReadModel",
  },
  "wiki.list": {
    method: "GET",
    pathTemplate: "/api/wiki",
    operationId: "wikiList",
    summary: "List source WikiObjects or per-target bible renderings by snapshot.",
    pathParams: [],
    responseSchema: "ApiWikiObjectListResponse",
  },
  "wiki.show": {
    method: "GET",
    pathTemplate: "/api/wiki/{wikiKind}/{objectId}",
    operationId: "wikiShow",
    summary: "Show one WikiObject with citations, media, badges, history, and dependency impact.",
    pathParams: ["wikiKind", "objectId"],
    responseSchema: "ApiWikiObjectShowResponse",
  },
  "wiki.history": {
    method: "GET",
    pathTemplate: "/api/wiki/{wikiKind}/{objectId}/history",
    operationId: "wikiHistory",
    summary: "Show immutable WikiObject history.",
    pathParams: ["wikiKind", "objectId"],
    responseSchema: "ApiWikiObjectHistoryResponse",
  },
  "wiki.edit": {
    method: "POST",
    pathTemplate: "/api/wiki/{wikiKind}/{objectId}/edit",
    operationId: "wikiEdit",
    summary: "Append a durable direct edit to a WikiObject.",
    pathParams: ["wikiKind", "objectId"],
    requestSchema: "ApiWikiWriteRequest",
    responseSchema: "ApiWikiObjectWriteResponse",
  },
  "wiki.feedback": {
    method: "POST",
    pathTemplate: "/api/wiki/{wikiKind}/{objectId}/feedback",
    operationId: "wikiFeedback",
    summary: "Append durable feedback to a WikiObject without awaiting inference.",
    pathParams: ["wikiKind", "objectId"],
    requestSchema: "ApiWikiWriteRequest",
    responseSchema: "ApiWikiObjectWriteResponse",
  },
  "wiki.apply": {
    method: "POST",
    pathTemplate: "/api/wiki/{wikiKind}/{objectId}/apply",
    operationId: "wikiApply",
    summary: "Apply a durable edit/feedback batch through one bounded enhancement.",
    pathParams: ["wikiKind", "objectId"],
    requestSchema: "ApiWikiApplyRequest",
    responseSchema: "ApiWikiObjectApplyResponse",
  },
  "queue.health": {
    method: "GET",
    pathTemplate: "/api/queue/health",
    operationId: "queueHealth",
    summary: "Queue health read model (outbox + jobs).",
    pathParams: [],
    responseSchema: "QueueHealthReadModel",
  },
  "assetDecisions.active": {
    method: "GET",
    pathTemplate: "/api/projects/{projectId}/locale-branches/{localeBranchId}/asset-decisions",
    operationId: "assetDecisionsActive",
    summary: "Active asset localization decisions.",
    pathParams: ["projectId", "localeBranchId"],
    responseSchema: "ApiAssetDecisionsResponse",
  },
  "assetDecisions.candidates": {
    method: "GET",
    pathTemplate:
      "/api/projects/{projectId}/locale-branches/{localeBranchId}/asset-decisions/candidates",
    operationId: "assetDecisionsCandidates",
    summary: "Candidate assets for localization decisions.",
    pathParams: ["projectId", "localeBranchId"],
    responseSchema: "ApiCandidateAssetsResponse",
  },
  "projects.decodeExtract": {
    method: "POST",
    pathTemplate: "/api/projects/decode-extract",
    operationId: "projectsDecodeExtract",
    summary: "Decode a game source (identify/inventory/extract) into a bridge bundle.",
    pathParams: [],
    requestSchema: "ApiProjectDecodeExtractRequest",
    responseSchema: "ApiProjectDecodeExtractResponse",
  },
  "imports.bridge": {
    method: "POST",
    pathTemplate: "/api/imports/bridge",
    operationId: "importsBridge",
    summary: "Import a bridge bundle.",
    pathParams: [],
    requestSchema: "ApiProjectImportRequest",
    responseSchema: "ApiProjectImportResponse",
  },
  "branches.draft": {
    method: "POST",
    pathTemplate: "/api/projects/{projectId}/branches",
    operationId: "branchesDraft",
    summary: "Draft a locale branch.",
    pathParams: ["projectId"],
    requestSchema: "ApiDraftBranchRequest",
    responseSchema: "ApiDraftBranchResponse",
  },
  "findings.record": {
    method: "POST",
    pathTemplate: "/api/projects/{projectId}/findings",
    operationId: "findingsRecord",
    summary: "Record a QA finding.",
    pathParams: ["projectId"],
    requestSchema: "ApiRecordFindingRequest",
    responseSchema: "ApiRecordFindingResponse",
  },
  "benchmarks.record": {
    method: "POST",
    pathTemplate: "/api/projects/{projectId}/benchmarks",
    operationId: "benchmarksRecord",
    summary: "Record a benchmark report.",
    pathParams: ["projectId"],
    requestSchema: "ApiRecordBenchmarkRequest",
    responseSchema: "ApiRecordBenchmarkResponse",
  },
  "runtimeEvidence.ingest": {
    method: "POST",
    pathTemplate: "/api/projects/{projectId}/runtime-evidence",
    operationId: "runtimeEvidenceIngest",
    summary: "Ingest a runtime evidence report.",
    pathParams: ["projectId"],
    requestSchema: "ApiRuntimeEvidenceRequest",
    responseSchema: "ApiRuntimeEvidenceResponse",
  },
  "settings.modelRouting.get": {
    method: "GET",
    pathTemplate: "/api/settings/model-routing",
    operationId: "settingsModelRoutingGet",
    summary: "Load project model routing settings and available provider/model/prompt choices.",
    pathParams: [],
    responseSchema: "ApiModelRoutingSettingsResponse",
  },
  "settings.modelRouting.save": {
    method: "POST",
    pathTemplate: "/api/settings/model-routing",
    operationId: "settingsModelRoutingSave",
    summary: "Save one project model-routing task route.",
    pathParams: [],
    requestSchema: "ApiSaveModelRoutingSettingsRequest",
    responseSchema: "ApiModelRoutingSettingsResponse",
  },
  "settings.branchPolicy.get": {
    method: "GET",
    pathTemplate:
      "/api/projects/{projectId}/locale-branches/{localeBranchId}/settings/branch-policy",
    operationId: "settingsBranchPolicyGet",
    summary: "Load editable branch policy and glossary reference state for a locale branch.",
    pathParams: ["projectId", "localeBranchId"],
    responseSchema: "ApiBranchPolicySettingsResponse",
  },
  "settings.branchPolicy.save": {
    method: "POST",
    pathTemplate:
      "/api/projects/{projectId}/locale-branches/{localeBranchId}/settings/branch-policy",
    operationId: "settingsBranchPolicySave",
    summary: "Save editable branch policy for a locale branch and refresh its glossary reference.",
    pathParams: ["projectId", "localeBranchId"],
    requestSchema: "ApiSaveBranchPolicySettingsRequest",
    responseSchema: "ApiBranchPolicySettingsResponse",
  },
  "settings.translationScope.get": {
    method: "GET",
    pathTemplate:
      "/api/projects/{projectId}/locale-branches/{localeBranchId}/settings/translation-scope",
    operationId: "settingsTranslationScopeGet",
    summary:
      "Load the config-driven translation scope (dialogue / +choices / +UI-text / +images) for a locale branch.",
    pathParams: ["projectId", "localeBranchId"],
    responseSchema: "ApiTranslationScopeSettingsResponse",
  },
  "settings.translationScope.save": {
    method: "POST",
    pathTemplate:
      "/api/projects/{projectId}/locale-branches/{localeBranchId}/settings/translation-scope",
    operationId: "settingsTranslationScopeSave",
    summary:
      "Save the config-driven translation scope for a locale branch. Read by the localize command.",
    pathParams: ["projectId", "localeBranchId"],
    requestSchema: "ApiSaveTranslationScopeSettingsRequest",
    responseSchema: "ApiTranslationScopeSettingsResponse",
  },
  "settings.localizationRunConfig.save": {
    method: "POST",
    pathTemplate:
      "/api/projects/{projectId}/locale-branches/{localeBranchId}/settings/localization-run-config",
    operationId: "settingsLocalizationRunConfigSave",
    summary:
      "Register the operator-local config, data root, pinned model/provider pair, and run directory for launch-pass.",
    pathParams: ["projectId", "localeBranchId"],
    requestSchema: "ApiSaveLocalizationRunConfigRequest",
    responseSchema: "ApiLocalizationRunConfigResponse",
  },
  "auth.ssoSettings.configure": {
    method: "POST",
    pathTemplate: "/api/settings/security/sso",
    operationId: "authSsoSettingsConfigure",
    summary: "Configure account SSO provider and security/session policy.",
    pathParams: [],
    requestSchema: "ApiConfigureAuthSsoSettingsRequest",
    responseSchema: "ApiConfigureAuthSsoSettingsResponse",
  },
  "auth.members.list": {
    method: "GET",
    pathTemplate: "/api/auth/members",
    operationId: "authMembersList",
    summary: "List account members and granted permission sets.",
    pathParams: [],
    responseSchema: "ApiMembersListResponse",
  },
  "auth.billing.seatUsage": {
    method: "GET",
    pathTemplate: "/api/auth/billing/seat-usage",
    operationId: "authBillingSeatUsage",
    summary: "Load account plan and seat usage derived from auth memberships.",
    pathParams: [],
    responseSchema: "ApiAuthBillingSeatUsageResponse",
  },
  "auth.identity": {
    method: "GET",
    pathTemplate: "/api/auth/identity",
    operationId: "authIdentity",
    summary: "Resolve the signed-in actor and their account memberships.",
    pathParams: [],
    responseSchema: "ApiAuthIdentityResponse",
  },
  // fnd-caps-context — the actor's Studio capability permission VIEW
  // (canFlag / canSteer / canReveal) resolved from exact
  // permission grants (capabilities, NOT roles).
  "auth.capabilities": {
    method: "GET",
    pathTemplate: "/api/auth/capabilities",
    operationId: "authCapabilities",
    summary: "Resolve the caller's Studio capability permission view (flag/decide/steer/reveal).",
    pathParams: [],
    responseSchema: "ApiAuthCapabilitiesResponse",
  },
} satisfies Readonly<Partial<Record<ItotoriApiRouteId, ItotoriApiRoute>>>;
