mod bgi_commands;
mod binary_patch_smoke;
mod evidence_commands;
mod golden_profile_commands;
mod helper_commands;
mod key_commands;
mod offset_map_commands;
mod partial_adapter;
mod readiness_commands;
mod reallive_commands;
mod rpgmaker_commands;
mod siglus_commands;
mod softpal_commands;
#[cfg(test)]
mod tests;
mod vault;
mod wolf_commands;
mod xp3_commands;
mod xp3_real_bytes_smoke;
include!("main_parts/001.rs");
include!("main_parts/002.rs");
