use super::*;
mod profile_init_redaction;

include!("tests/whole_seen.rs");
include!("tests/fixture_tools.rs");
include!("tests/helper_support.rs");
include!("tests/helper_dry_run.rs");
include!("tests/helper_registry.rs");
include!("tests/helper_results.rs");
include!("tests/adapter_support.rs");
include!("tests/preflight_support.rs");
include!("tests/report_support.rs");
include!("tests/engine_dispatch.rs");
include!("tests/delta_apply_reports.rs");
include!("tests/patch_staging.rs");
include!("tests/reallive_patch.rs");
include!("tests/patch_preflight.rs");
include!("tests/golden.rs");
include!("tests/detect_rpgmaker.rs");
include!("tests/siglus_parser.rs");
include!("tests/xp3_detection.rs");
include!("tests/xp3_inventory.rs");
include!("tests/variant_detection.rs");
include!("tests/profile_validation.rs");
include!("tests/xp3_profile.rs");
include!("tests/xp3_archive.rs");
include!("tests/rpgmaker_media.rs");
include!("tests/gameexe.rs");
