export const projectFeedbackLedgerPermissionGateMatrixExpected = [
  {
    denialFixture: "missing permission actor user-without-required-permission",
    mutation: "ItotoriProjectRepository.reset",
    requiredPermission: "system.reset",
    successFixture: "repository.test.ts reset coverage",
  },
  {
    denialFixture: "missing permission actor user-without-required-permission",
    mutation: "ItotoriProjectRepository.importSourceBundle",
    requiredPermission: "project.import",
    successFixture: "repository.test.ts import coverage",
  },
  {
    denialFixture: "missing permission actor user-without-required-permission",
    mutation: "ItotoriProjectRepository.ensureRunProjectScope",
    requiredPermission: "project.import",
    successFixture: "project-run-scope-provisioning.test.ts run scope provisioning coverage",
  },
  {
    denialFixture: "missing permission actor user-without-required-permission",
    mutation: "ItotoriProjectRepository.saveDrafts",
    requiredPermission: "draft.write",
    successFixture: "repository.test.ts draft persistence coverage",
  },
  {
    denialFixture: "missing permission actor user-without-required-permission",
    mutation: "ItotoriProjectRepository.loadLocaleBranchDraftTexts",
    requiredPermission: "catalog.read",
    successFixture: "context-correction-redrafter durable draft verification coverage",
  },
  {
    denialFixture: "missing permission actor user-without-required-permission",
    mutation: "ItotoriProjectRepository.savePatchExport",
    requiredPermission: "patch.export",
    successFixture: "repository.test.ts patch export persistence coverage",
  },
  {
    denialFixture: "missing permission actor user-without-required-permission",
    mutation: "ItotoriProjectRepository.saveRuntimeReport",
    requiredPermission: "runtime.ingest",
    successFixture: "repository.test.ts runtime report persistence coverage",
  },
  {
    denialFixture: "missing permission actor user-without-required-permission",
    mutation: "ItotoriProjectRepository.appendEvent",
    requiredPermission: "runtime.ingest",
    successFixture: "repository.test.ts event coverage",
  },
  {
    denialFixture: "missing permission actor user-without-required-permission",
    mutation: "ItotoriProjectRepository.recordFinding",
    requiredPermission: "runtime.ingest",
    successFixture: "repository.test.ts finding coverage",
  },
  {
    denialFixture: "missing permission actor user-without-required-permission",
    mutation: "ItotoriProjectRepository.linkArtifact",
    requiredPermission: "runtime.ingest",
    successFixture: "repository.test.ts artifact coverage",
  },
  {
    denialFixture: "missing permission actor user-without-required-permission",
    mutation: "ItotoriProjectRepository.getRuntimeStatus",
    requiredPermission: "catalog.read",
    successFixture: "repository.test.ts runtime status coverage",
  },
  {
    denialFixture: "missing permission actor user-without-required-permission",
    mutation: "ItotoriProjectRepository.recordBenchmarkArtifactWithProviderLedger",
    requiredPermission: "runtime.ingest",
    successFixture: "model-ledger-repository.test.ts atomic benchmark artifact coverage",
  },
  {
    denialFixture: "missing permission actor user-without-required-permission",
    mutation: "ItotoriFeedbackRepository.importManualFeedback",
    requiredPermission: "feedback.import",
    successFixture: "repository.test.ts manual feedback coverage",
  },
  {
    denialFixture: "missing permission actor user-without-required-permission",
    mutation: "ItotoriFeedbackRepository.loadManualFeedbackCorrectionContext",
    requiredPermission: "feedback.import",
    successFixture: "repository.test.ts manual feedback correction context coverage",
  },
  {
    denialFixture: "missing permission actor user-without-required-permission",
    mutation: "ItotoriFeedbackRepository.listUnitBoundFeedback",
    requiredPermission: "feedback.import",
    successFixture: "repository.test.ts unit-bound feedback coverage",
  },
  {
    denialFixture: "missing permission actor user-without-required-permission",
    mutation: "ItotoriModelLedgerRepository.recordProviderRun",
    requiredPermission: "runtime.ingest",
    successFixture: "model-ledger-repository.test.ts provider run coverage",
  },
  {
    denialFixture: "missing permission actor user-without-required-permission",
    mutation: "ItotoriModelLedgerRepository.countZdrEnforcedByPair",
    requiredPermission: "catalog.read",
    successFixture: "model-ledger-repository.test.ts ZDR-enforced count coverage",
  },
  {
    denialFixture: "missing permission actor user-without-required-permission",
    mutation: "ItotoriModelLedgerRepository.countCostKindsByPair",
    requiredPermission: "catalog.read",
    successFixture: "model-ledger-repository.test.ts cost kind count coverage",
  },
  {
    denialFixture: "missing permission actor user-without-required-permission",
    mutation: "ItotoriModelLedgerRepository.getProjectCostReport",
    requiredPermission: "catalog.read",
    successFixture: "model-ledger-repository.test.ts project cost report coverage",
  },
  {
    denialFixture: "missing permission actor user-without-required-permission",
    mutation: "ItotoriModelLedgerRepository.getCostLedgerDrilldown",
    requiredPermission: "catalog.read",
    successFixture: "model-ledger-repository.test.ts cost drilldown coverage",
  },
] as const;
