export const permissionGateMatrixExpectedPart2 = [
  {
    denialFixture: "missing permission actor user-without-required-permission",
    mutation: "ItotoriModelLedgerRepository.getProjectTelemetryTimeseries",
    requiredPermission: "catalog.read",
    successFixture: "model-ledger-repository.test.ts telemetry timeseries coverage",
  },
  {
    denialFixture: "missing permission actor user-without-required-permission",
    mutation: "ItotoriEventQueueRepository.appendOutboxEvent",
    requiredPermission: "queue.manage",
    successFixture: "event-queue-repository.test.ts outbox event coverage",
  },
  {
    denialFixture: "missing permission actor user-without-required-permission",
    mutation: "ItotoriEventQueueRepository.enqueueJob",
    requiredPermission: "queue.manage",
    successFixture: "event-queue-repository.test.ts job coverage",
  },
  {
    denialFixture: "missing permission actor user-without-required-permission",
    mutation: "ItotoriEventQueueRepository.enqueueJobs",
    requiredPermission: "queue.manage",
    successFixture: "event-queue-repository.test.ts atomic job chain coverage",
  },
  {
    denialFixture: "missing permission actor user-without-required-permission",
    mutation: "ItotoriEventQueueRepository.appendOutboxEventWithJobs",
    requiredPermission: "queue.manage",
    successFixture: "event-queue-repository.test.ts outbox plus jobs coverage",
  },
  {
    denialFixture: "missing permission actor user-without-required-permission",
    mutation: "ItotoriEventQueueRepository.claimOutboxEvents",
    requiredPermission: "queue.manage",
    successFixture: "event-queue-repository.test.ts outbox claim coverage",
  },
  {
    denialFixture: "missing permission actor user-without-required-permission",
    mutation: "ItotoriEventQueueRepository.markOutboxEventPublished",
    requiredPermission: "queue.manage",
    successFixture: "event-queue-repository.test.ts outbox publish coverage",
  },
  {
    denialFixture: "missing permission actor user-without-required-permission",
    mutation: "ItotoriEventQueueRepository.markOutboxEventFailed",
    requiredPermission: "queue.manage",
    successFixture: "event-queue-repository.test.ts outbox failure coverage",
  },
  {
    denialFixture: "missing permission actor user-without-required-permission",
    mutation: "ItotoriEventQueueRepository.recoverExpiredOutboxLeases",
    requiredPermission: "queue.manage",
    successFixture: "event-queue-repository.test.ts outbox lease recovery coverage",
  },
  {
    denialFixture: "missing permission actor user-without-required-permission",
    mutation: "ItotoriEventQueueRepository.claimJobs",
    requiredPermission: "queue.manage",
    successFixture: "event-queue-repository.test.ts job claim coverage",
  },
  {
    denialFixture: "missing permission actor user-without-required-permission",
    mutation: "ItotoriEventQueueRepository.completeJob",
    requiredPermission: "queue.manage",
    successFixture: "event-queue-repository.test.ts job completion coverage",
  },
  {
    denialFixture: "missing permission actor user-without-required-permission",
    mutation: "ItotoriEventQueueRepository.failJob",
    requiredPermission: "queue.manage",
    successFixture: "event-queue-repository.test.ts job failure coverage",
  },
  {
    denialFixture: "missing permission actor user-without-required-permission",
    mutation: "ItotoriEventQueueRepository.recoverExpiredJobLeases",
    requiredPermission: "queue.manage",
    successFixture: "event-queue-repository.test.ts job lease recovery coverage",
  },
  {
    denialFixture: "missing permission actor user-without-required-permission",
    mutation: "ItotoriEventQueueRepository.getOutboxEvent",
    requiredPermission: "queue.read",
    successFixture: "event-queue-repository.test.ts authorized outbox read coverage",
  },
  {
    denialFixture: "missing permission actor user-without-required-permission",
    mutation: "ItotoriEventQueueRepository.getJob",
    requiredPermission: "queue.read",
    successFixture: "event-queue-repository.test.ts authorized job read coverage",
  },
  {
    denialFixture: "missing permission actor user-without-required-permission",
    mutation: "ItotoriEventQueueRepository.getJobEvents",
    requiredPermission: "queue.read",
    successFixture: "job-events-audit.test.ts job event read coverage",
  },
  {
    denialFixture: "missing permission actor user-without-required-permission",
    mutation: "ItotoriEventQueueRepository.pruneJobEvents",
    requiredPermission: "queue.manage",
    successFixture: "job-events-audit.test.ts retention prune coverage",
  },
  {
    denialFixture: "missing permission actor user-without-required-permission",
    mutation: "ItotoriEventQueueRepository.loadQueueHealth",
    requiredPermission: "queue.read",
    successFixture: "event-queue-queue-health.test.ts queue health read coverage",
  },
  {
    denialFixture: "missing permission actor user-without-required-permission",
    mutation: "ItotoriCatalogRepository.recordSourceProvenance",
    requiredPermission: "catalog.write",
    successFixture: "catalog-repository.test.ts source provenance coverage",
  },
  {
    denialFixture: "missing permission actor user-without-required-permission",
    mutation: "ItotoriCatalogRepository.upsertWork",
    requiredPermission: "catalog.write",
    successFixture: "catalog-repository.test.ts work coverage",
  },
] as const;
