export const localizationWorkflowPermissionGateMatrixExpected = [
  {
    denialFixture: "missing permission actor user-without-required-permission",
    mutation: "ItotoriSourceUnitRepository.loadSourceUnitsForScope",
    requiredPermission: "catalog.read",
    successFixture: "source-unit-repository.test.ts source-unit scope coverage",
  },
  {
    denialFixture: "missing permission actor user-without-required-permission",
    mutation: "ItotoriSourceUnitRepository.resolveAddressableBridgeUnits",
    requiredPermission: "catalog.read",
    successFixture: "unit-feedback-live-db.test.ts wiki entry source-unit resolution coverage",
  },
  {
    denialFixture: "missing permission actor user-without-required-permission",
    mutation: "ItotoriTranslationBatchRepository.saveBatches",
    requiredPermission: "draft.write",
    successFixture: "translation-batch-repository.test.ts save coverage",
  },
  {
    denialFixture: "missing permission actor user-without-required-permission",
    mutation: "ItotoriTranslationBatchRepository.loadBatches",
    requiredPermission: "catalog.read",
    successFixture: "translation-batch-repository.test.ts load coverage",
  },
  {
    denialFixture: "missing permission actor user-without-required-permission",
    mutation: "ItotoriTranslationBatchRepository.loadBatchById",
    requiredPermission: "catalog.read",
    successFixture: "translation-batch-repository.test.ts load-by-id coverage",
  },
  {
    denialFixture: "missing permission actor user-without-required-permission",
    mutation: "ItotoriConformanceRepository.saveConformanceRun",
    requiredPermission: "runtime.ingest",
    successFixture: "conformance-repository.test.ts save coverage",
  },
  {
    denialFixture: "missing permission actor user-without-required-permission",
    mutation: "ItotoriConformanceRepository.loadConformanceRun",
    requiredPermission: "catalog.read",
    successFixture: "conformance-repository.test.ts load coverage",
  },
  {
    denialFixture: "missing permission actor user-without-required-permission",
    mutation: "EngineCapabilityReportRepository.writeMatrix",
    requiredPermission: "project.import",
    successFixture: "engine-capability-report-repository.test.ts write matrix coverage",
  },
  {
    denialFixture: "missing permission actor user-without-required-permission",
    mutation: "EngineCapabilityReportRepository.recordCapabilityEvidence",
    requiredPermission: "project.import",
    successFixture: "engine-capability-report-repository.test.ts capability evidence coverage",
  },
  {
    denialFixture: "missing permission actor user-without-required-permission",
    mutation: "ItotoriDraftJobRepository.createDraftJob",
    requiredPermission: "draft.write",
    successFixture: "draft-job-repository.test.ts create draft job coverage",
  },
  {
    denialFixture: "missing permission actor user-without-required-permission",
    mutation: "ItotoriDraftJobRepository.recordAttempt",
    requiredPermission: "draft.write",
    successFixture: "draft-job-repository.test.ts record attempt coverage",
  },
  {
    denialFixture: "missing permission actor user-without-required-permission",
    mutation: "ItotoriDraftJobRepository.markAttemptSucceeded",
    requiredPermission: "draft.write",
    successFixture: "draft-job-repository.test.ts mark attempt succeeded coverage",
  },
  {
    denialFixture: "missing permission actor user-without-required-permission",
    mutation: "ItotoriDraftJobRepository.markAttemptFailed",
    requiredPermission: "draft.write",
    successFixture: "draft-job-repository.test.ts mark attempt failed coverage",
  },
  {
    denialFixture: "missing permission actor user-without-required-permission",
    mutation: "ItotoriDraftJobRepository.cancelDraftJob",
    requiredPermission: "draft.write",
    successFixture: "draft-job-repository.test.ts cancel draft job coverage",
  },
  {
    denialFixture: "missing permission actor user-without-required-permission",
    mutation: "ItotoriDraftJobRepository.loadDraftJob",
    requiredPermission: "catalog.read",
    successFixture: "draft-job-repository.test.ts load draft job coverage",
  },
  {
    denialFixture: "missing permission actor user-without-required-permission",
    mutation: "ItotoriDraftJobRepository.loadDraftJobsByProject",
    requiredPermission: "catalog.read",
    successFixture: "draft-job-repository.test.ts load draft jobs by project coverage",
  },
  {
    denialFixture: "missing permission actor user-without-required-permission",
    mutation: "ItotoriDraftJobRepository.loadDraftJobAttempts",
    requiredPermission: "catalog.read",
    successFixture: "draft-job-repository.test.ts load draft job attempts coverage",
  },
  {
    denialFixture: "missing permission actor user-without-required-permission",
    mutation: "ItotoriAssetLocalizationDecisionRepository.loadActiveDecisions",
    requiredPermission: "catalog.read",
    successFixture: "asset-localization-decision-repository.test.ts load active decisions coverage",
  },
  {
    denialFixture: "missing permission actor user-without-required-permission",
    mutation: "ItotoriAssetLocalizationDecisionRepository.loadCandidateAssets",
    requiredPermission: "catalog.read",
    successFixture: "asset-localization-decision-repository.test.ts load candidate assets coverage",
  },
  {
    denialFixture: "missing permission actor user-without-required-permission",
    mutation: "ItotoriAssetLocalizationDecisionRepository.loadDecisionHistory",
    requiredPermission: "catalog.read",
    successFixture: "asset-localization-decision-repository.test.ts load decision history coverage",
  },
] as const;
