export const crawlerAndLanguageAssetsPermissionGateMatrixExpected = [
  {
    denialFixture: "missing permission actor user-without-required-permission",
    mutation: "ItotoriCatalogCrawlerRepository.markStepFailed",
    requiredPermission: "catalog.write",
    successFixture: "catalog-crawler-repository.test.ts failed marker coverage",
  },
  {
    denialFixture: "missing permission actor user-without-required-permission",
    mutation: "ItotoriCatalogCrawlerRepository.saveCheckpoint",
    requiredPermission: "catalog.write",
    successFixture: "catalog-crawler-repository.test.ts checkpoint write coverage",
  },
  {
    denialFixture: "missing permission actor user-without-required-permission",
    mutation: "ItotoriCatalogCrawlerRepository.saveRateLimit",
    requiredPermission: "catalog.write",
    successFixture: "catalog-crawler-repository.test.ts rate-limit write coverage",
  },
  {
    denialFixture: "missing permission actor user-without-required-permission",
    mutation: "ItotoriCatalogCrawlerRepository.completeCrawlerJob",
    requiredPermission: "catalog.write",
    successFixture: "catalog-crawler-repository.test.ts crawler job completion coverage",
  },
  {
    denialFixture: "missing permission actor user-without-required-permission",
    mutation: "ItotoriCatalogCrawlerRepository.failCrawlerJob",
    requiredPermission: "catalog.write",
    successFixture: "catalog-crawler-repository.test.ts crawler job failure coverage",
  },
  {
    denialFixture: "missing permission actor user-without-required-permission",
    mutation: "ItotoriBranchReferenceRepository.resolveBranchPolicyGlossaryReference",
    requiredPermission: "catalog.read",
    successFixture: "terminology-repository.test.ts branch-scoped policy/glossary coverage",
  },
  {
    denialFixture: "missing permission actor user-without-required-permission",
    mutation: "ItotoriBranchReferenceRepository.updateBranchPolicyGlossaryReference",
    requiredPermission: "draft.write",
    successFixture: "terminology-repository.test.ts branch reference update coverage",
  },
  {
    denialFixture: "missing permission actor user-without-required-permission",
    mutation: "ItotoriStyleGuideRepository.createVersion",
    requiredPermission: "draft.write",
    successFixture: "style-guide-repository.test.ts version persistence coverage",
  },
  {
    denialFixture: "missing permission actor user-without-required-permission",
    mutation: "ItotoriStyleGuideRepository.authorizeApproval",
    requiredPermission: "style_guide.approve",
    successFixture: "style-guide-repository.test.ts approval authorization coverage",
  },
  {
    denialFixture: "missing permission actor user-without-required-permission",
    mutation: "ItotoriStyleGuideRepository.approveVersion",
    requiredPermission: "style_guide.approve",
    successFixture: "style-guide-repository.test.ts approval coverage",
  },
  {
    denialFixture: "missing permission actor user-without-required-permission",
    mutation: "ItotoriTerminologyRepository.upsertTerm",
    requiredPermission: "draft.write",
    successFixture: "terminology-repository.test.ts term persistence coverage",
  },
  {
    denialFixture: "missing permission actor user-without-required-permission",
    mutation: "ItotoriTerminologyRepository.searchTerms",
    requiredPermission: "catalog.read",
    successFixture: "terminology-repository.test.ts term search coverage",
  },
  {
    denialFixture: "missing permission actor user-without-required-permission",
    mutation: "ItotoriTerminologyRepository.listConflicts",
    requiredPermission: "catalog.read",
    successFixture: "terminology-repository.test.ts conflict listing coverage",
  },
  {
    denialFixture: "missing permission actor user-without-required-permission",
    mutation: "ItotoriTerminologyRepository.getGlossaryContext",
    requiredPermission: "catalog.read",
    successFixture: "terminology-repository.test.ts glossary context coverage",
  },
  {
    denialFixture: "missing permission actor user-without-required-permission",
    mutation: "ItotoriTranslationMemoryRepository.upsertSegment",
    requiredPermission: "draft.write",
    successFixture: "translation-memory-repository.test.ts segment persistence coverage",
  },
  {
    denialFixture: "missing permission actor user-without-required-permission",
    mutation: "ItotoriTranslationMemoryRepository.recordReuse",
    requiredPermission: "draft.write",
    successFixture: "translation-memory-repository.test.ts reuse provenance coverage",
  },
  {
    denialFixture: "missing permission actor user-without-required-permission",
    mutation: "ItotoriExactSearchDocumentRepository.refreshDocuments",
    requiredPermission: "project.import",
    successFixture: "exact-search-document-repository.test.ts refresh coverage",
  },
  {
    denialFixture: "missing permission actor user-without-required-permission",
    mutation: "ItotoriExactSearchDocumentRepository.searchExact",
    requiredPermission: "catalog.read",
    successFixture: "exact-search-document-repository.test.ts search.exact coverage",
  },
  {
    denialFixture: "missing permission actor user-without-required-permission",
    mutation: "ItotoriSourceUnitRepository.currentSourceHashes",
    requiredPermission: "catalog.read",
    successFixture: "source-unit-repository.test.ts source-unit hash coverage",
  },
  {
    denialFixture: "missing permission actor user-without-required-permission",
    mutation: "ItotoriSourceUnitRepository.loadSourceUnits",
    requiredPermission: "catalog.read",
    successFixture: "source-unit-repository.test.ts source-unit hydration coverage",
  },
] as const;
