import type { RepositoryPermissionGateCase } from "./authorization-matrix.test.helpers.js";
import {
  branchReferenceGate,
  styleGuideGate,
  terminologyGate,
  translationMemoryGate,
  exactSearchGate,
  sourceUnitGate,
  translationBatchGate,
  conformanceGate,
  engineCapabilityReportGate,
  draftJobGate,
  assetLocalizationDecisionGate,
  auditFindingGate,
  principalGate,
  principalExportGate,
  authSsoSettingsGate,
  authMemberManagementGate,
  authBillingSeatGate,
} from "./authorization-matrix.test.factories.js";

export const repositoryPermissionGateMatrixPart2 = [
  branchReferenceGate(
    "updateBranchPolicyGlossaryReference",
    "draftWrite",
    "terminology-repository.test.ts branch reference update coverage",
    (repo) =>
      repo.updateBranchPolicyGlossaryReference(deniedActor, {
        projectId: "project",
        localeBranchId: "locale",
        updateReason: "permission_denial_fixture",
      }),
  ),
  styleGuideGate(
    "createVersion",
    "draftWrite",
    "style-guide-repository.test.ts version persistence coverage",
    (repo) => repo.createVersion(deniedActor, undefined as never),
  ),
  styleGuideGate(
    "authorizeApproval",
    "styleGuideApprove",
    "style-guide-repository.test.ts approval authorization coverage",
    (repo) => repo.authorizeApproval(deniedActor),
  ),
  styleGuideGate(
    "approveVersion",
    "styleGuideApprove",
    "style-guide-repository.test.ts approval coverage",
    (repo) => repo.approveVersion(deniedActor, undefined as never),
  ),
  terminologyGate(
    "upsertTerm",
    "draftWrite",
    "terminology-repository.test.ts term persistence coverage",
    (repo) => repo.upsertTerm(deniedActor, undefined as never),
  ),
  terminologyGate(
    "searchTerms",
    "catalogRead",
    "terminology-repository.test.ts term search coverage",
    (repo) => repo.searchTerms(deniedActor, undefined as never),
  ),
  terminologyGate(
    "listConflicts",
    "catalogRead",
    "terminology-repository.test.ts conflict listing coverage",
    (repo) => repo.listConflicts(deniedActor),
  ),
  terminologyGate(
    "getGlossaryContext",
    "catalogRead",
    "terminology-repository.test.ts glossary context coverage",
    (repo) => repo.getGlossaryContext(deniedActor, undefined as never),
  ),
  translationMemoryGate(
    "upsertSegment",
    "draftWrite",
    "translation-memory-repository.test.ts segment persistence coverage",
    (repo) => repo.upsertSegment(deniedActor, undefined as never),
  ),
  translationMemoryGate(
    "recordReuse",
    "draftWrite",
    "translation-memory-repository.test.ts reuse provenance coverage",
    (repo) => repo.recordReuse(deniedActor, undefined as never),
  ),
  exactSearchGate(
    "refreshDocuments",
    "projectImport",
    "exact-search-document-repository.test.ts refresh coverage",
    (repo) => repo.refreshDocuments(deniedActor, undefined as never),
  ),
  exactSearchGate(
    "searchExact",
    "catalogRead",
    "exact-search-document-repository.test.ts search.exact coverage",
    (repo) => repo.searchExact(deniedActor, undefined as never),
  ),
  sourceUnitGate(
    "currentSourceHashes",
    "catalogRead",
    "source-unit-repository.test.ts source-unit hash coverage",
    (repo) => repo.currentSourceHashes(deniedActor, undefined as never),
  ),
  sourceUnitGate(
    "loadSourceUnits",
    "catalogRead",
    "source-unit-repository.test.ts source-unit hydration coverage",
    (repo) => repo.loadSourceUnits(deniedActor, undefined as never),
  ),
  sourceUnitGate(
    "loadSourceUnitsForScope",
    "catalogRead",
    "source-unit-repository.test.ts source-unit scope coverage",
    (repo) => repo.loadSourceUnitsForScope(deniedActor, undefined as never),
  ),
  sourceUnitGate(
    "resolveAddressableBridgeUnits",
    "catalogRead",
    "unit-feedback-live-db.test.ts wiki entry source-unit resolution coverage",
    (repo) => repo.resolveAddressableBridgeUnits(deniedActor, undefined as never),
  ),
  translationBatchGate(
    "saveBatches",
    "draftWrite",
    "translation-batch-repository.test.ts save coverage",
    (repo) => repo.saveBatches(deniedActor, undefined as never),
  ),
  translationBatchGate(
    "loadBatches",
    "catalogRead",
    "translation-batch-repository.test.ts load coverage",
    (repo) => repo.loadBatches(deniedActor, undefined as never),
  ),
  translationBatchGate(
    "loadBatchById",
    "catalogRead",
    "translation-batch-repository.test.ts load-by-id coverage",
    (repo) => repo.loadBatchById(deniedActor, "batch-id"),
  ),
  conformanceGate(
    "saveConformanceRun",
    "runtimeIngest",
    "conformance-repository.test.ts save coverage",
    (repo) => repo.saveConformanceRun(deniedActor, undefined as never),
  ),
  conformanceGate(
    "loadConformanceRun",
    "catalogRead",
    "conformance-repository.test.ts load coverage",
    (repo) => repo.loadConformanceRun(deniedActor, "conformance-run-id"),
  ),
  engineCapabilityReportGate(
    "writeMatrix",
    "projectImport",
    "engine-capability-report-repository.test.ts write matrix coverage",
    (repo) =>
      repo.writeMatrix(deniedActor, {
        adapterId: "kaifuu.test",
        identify: { kind: "supported" },
        inventory: { kind: "supported" },
        extract: { kind: "supported" },
        patch: { kind: "supported" },
      }),
  ),
  engineCapabilityReportGate(
    "recordCapabilityEvidence",
    "projectImport",
    "engine-capability-report-repository.test.ts capability evidence coverage",
    (repo) => repo.recordCapabilityEvidence(deniedActor, undefined as never),
  ),
  draftJobGate(
    "createDraftJob",
    "draftWrite",
    "draft-job-repository.test.ts create draft job coverage",
    (repo) => repo.createDraftJob(deniedActor, undefined as never),
  ),
  draftJobGate(
    "recordAttempt",
    "draftWrite",
    "draft-job-repository.test.ts record attempt coverage",
    (repo) => repo.recordAttempt(deniedActor, "draft-job", undefined as never),
  ),
  draftJobGate(
    "markAttemptSucceeded",
    "draftWrite",
    "draft-job-repository.test.ts mark attempt succeeded coverage",
    (repo) => repo.markAttemptSucceeded(deniedActor, "draft-job-attempt", new Date()),
  ),
  draftJobGate(
    "markAttemptFailed",
    "draftWrite",
    "draft-job-repository.test.ts mark attempt failed coverage",
    (repo) => repo.markAttemptFailed(deniedActor, "draft-job-attempt", "reason", false, new Date()),
  ),
  draftJobGate(
    "cancelDraftJob",
    "draftWrite",
    "draft-job-repository.test.ts cancel draft job coverage",
    (repo) => repo.cancelDraftJob(deniedActor, "draft-job"),
  ),
  draftJobGate(
    "loadDraftJob",
    "catalogRead",
    "draft-job-repository.test.ts load draft job coverage",
    (repo) => repo.loadDraftJob(deniedActor, "draft-job"),
  ),
  draftJobGate(
    "loadDraftJobsByProject",
    "catalogRead",
    "draft-job-repository.test.ts load draft jobs by project coverage",
    (repo) => repo.loadDraftJobsByProject(deniedActor, "project"),
  ),
  draftJobGate(
    "loadDraftJobAttempts",
    "catalogRead",
    "draft-job-repository.test.ts load draft job attempts coverage",
    (repo) => repo.loadDraftJobAttempts(deniedActor, "draft-job"),
  ),
  assetLocalizationDecisionGate(
    "loadActiveDecisions",
    "catalogRead",
    "asset-localization-decision-repository.test.ts load active decisions coverage",
    (repo) => repo.loadActiveDecisions(deniedActor, "project", "locale"),
  ),
  assetLocalizationDecisionGate(
    "loadCandidateAssets",
    "catalogRead",
    "asset-localization-decision-repository.test.ts load candidate assets coverage",
    (repo) => repo.loadCandidateAssets(deniedActor, "project", "locale"),
  ),
  assetLocalizationDecisionGate(
    "loadDecisionHistory",
    "catalogRead",
    "asset-localization-decision-repository.test.ts load decision history coverage",
    (repo) =>
      repo.loadDecisionHistory(deniedActor, "project", "locale", {
        kind: "bridgeAssetRef",
        ref: "asset.json#example",
      }),
  ),
  assetLocalizationDecisionGate(
    "loadDecisionsByPolicy",
    "catalogRead",
    "asset-localization-decision-repository.test.ts load decisions by policy coverage",
    (repo) => repo.loadDecisionsByPolicy(deniedActor, "project", "locale", "keep_original"),
  ),
  auditFindingGate(
    "recordFinding",
    "auditWrite",
    "audit-finding-repository.test.ts record finding coverage",
    (repo) => repo.recordFinding(deniedActor, undefined as never),
  ),
  auditFindingGate(
    "loadFindingsByNode",
    "catalogRead",
    "audit-finding-repository.test.ts load findings by node coverage",
    (repo) => repo.loadFindingsByNode(deniedActor, "TEST-NODE-AUDIT-FINDING"),
  ),
  auditFindingGate(
    "loadFindingsByReport",
    "catalogRead",
    "audit-finding-repository.test.ts load findings by report coverage",
    (repo) => repo.loadFindingsByReport(deniedActor, "AUDIT-REPORT-1"),
  ),
  auditFindingGate(
    "loadOpenFindings",
    "catalogRead",
    "audit-finding-repository.test.ts load open findings coverage",
    (repo) => repo.loadOpenFindings(deniedActor),
  ),
  auditFindingGate(
    "markFindingFixed",
    "auditWrite",
    "audit-finding-repository.test.ts mark finding fixed coverage",
    (repo) => repo.markFindingFixed(deniedActor, "audit-finding-x", new Date()),
  ),
  auditFindingGate(
    "markFindingSuperseded",
    "auditWrite",
    "audit-finding-repository.test.ts mark finding superseded coverage",
    (repo) =>
      repo.markFindingSuperseded(deniedActor, "audit-finding-old", "audit-finding-new", new Date()),
  ),
  principalGate(
    "createAccount",
    "authAdmin",
    "principal-repository.test.ts create account coverage",
    (repo) => repo.createAccount(deniedActor, undefined as never),
  ),
  principalGate(
    "createPrincipal",
    "authAdmin",
    "principal-repository.test.ts create principal coverage",
    (repo) => repo.createPrincipal(deniedActor, undefined as never),
  ),
  principalGate(
    "createPermissionSet",
    "authPermissionsManage",
    "principal-repository.test.ts create permission set coverage",
    (repo) => repo.createPermissionSet(deniedActor, undefined as never),
  ),
  principalGate(
    "addPermissionToSet",
    "authPermissionsManage",
    "permission-set-model.test.ts add permission to set coverage",
    (repo) => repo.addPermissionToSet(deniedActor, undefined as never),
  ),
  principalGate(
    "removePermissionFromSet",
    "authPermissionsManage",
    "permission-set-model.test.ts remove permission from set coverage",
    (repo) => repo.removePermissionFromSet(deniedActor, undefined as never),
  ),
  principalGate(
    "renamePermissionSet",
    "authPermissionsManage",
    "permission-set-model.test.ts rename permission set coverage",
    (repo) => repo.renamePermissionSet(deniedActor, undefined as never),
  ),
  principalGate(
    "deletePermissionSet",
    "authPermissionsManage",
    "permission-set-model.test.ts delete permission set coverage",
    (repo) => repo.deletePermissionSet(deniedActor, undefined as never),
  ),
  principalGate(
    "grantPermissionSet",
    "authPermissionsManage",
    "principal-repository.test.ts grant permission set coverage",
    (repo) => repo.grantPermissionSet(deniedActor, undefined as never),
  ),
  principalGate(
    "revokePermissionSet",
    "authPermissionsManage",
    "auth-grant-audit-log.test.ts revoke permission set coverage",
    (repo) => repo.revokePermissionSet(deniedActor, undefined as never),
  ),
  principalGate(
    "grantDirectPermission",
    "authPermissionsManage",
    "principal-repository.test.ts grant direct permission coverage",
    (repo) => repo.grantDirectPermission(deniedActor, undefined as never),
  ),
  principalGate(
    "mapProviderClaimToDirectPermission",
    "authAdmin",
    "effective-permission-resolver.test.ts provider claim mapping coverage",
    (repo) => repo.mapProviderClaimToDirectPermission(deniedActor, undefined as never),
  ),
  principalGate(
    "revokeDirectPermission",
    "authPermissionsManage",
    "auth-grant-audit-log.test.ts revoke direct permission coverage",
    (repo) => repo.revokeDirectPermission(deniedActor, undefined as never),
  ),
  principalGate(
    "loadPrincipal",
    "authAdmin",
    "principal-repository.test.ts load principal coverage",
    (repo) => repo.loadPrincipal(deniedActor, "principal-x"),
  ),
  principalGate(
    "resolvePrincipalPermissions",
    "authPermissionsManage",
    "principal-repository.test.ts resolve principal permissions coverage",
    (repo) => repo.resolvePrincipalPermissions(deniedActor, "principal-x"),
  ),
  principalExportGate(
    "listAccountPermissionSets",
    "authPermissionsManage",
    "principal-repository.test.ts permission set helper coverage",
    (db) => listAccountPermissionSets(db, deniedActor, "account-denied"),
  ),
  principalExportGate(
    "loadPermissionSetAccountId",
    "authPermissionsManage",
    "principal-repository.test.ts permission set helper coverage",
    (db) => loadPermissionSetAccountId(db, deniedActor, "permission-set-denied"),
  ),
  authSsoSettingsGate(
    "configureSettings",
    "authSsoManage",
    "auth-sso-settings-repository.test.ts configure settings coverage",
    (repo) => repo.configureSettings(deniedActor, undefined as never),
  ),
  authMemberManagementGate(
    "inviteMember",
    "authMembersManage",
    "auth-member-management-repository.test.ts invite member coverage",
    (repo) => repo.inviteMember(deniedActor, undefined as never),
  ),
  authMemberManagementGate(
    "acceptInvitation",
    "authMembersManage",
    "auth-member-management-repository.test.ts accept invitation coverage",
    (repo) => repo.acceptInvitation(deniedActor, undefined as never),
  ),
  authMemberManagementGate(
    "listMembers",
    "authMembersManage",
    "auth-member-management-repository.test.ts list members coverage",
    (repo) => repo.listMembers(deniedActor, "account-denied"),
  ),
  authMemberManagementGate(
    "removeMember",
    "authMembersManage",
    "auth-member-management-repository.test.ts remove member coverage",
    (repo) => repo.removeMember(deniedActor, undefined as never),
  ),
  authBillingSeatGate(
    "loadSeatUsage",
    "authMembersManage",
    "auth-billing-seat-repository.test.ts load seat usage coverage",
    (repo) => repo.loadSeatUsage(deniedActor, "account-denied"),
  ),
] satisfies readonly RepositoryPermissionGateCase[];
