Feature: Authenticate people and administer isolated access
  Identity proves who is acting; application grants independently decide what
  that actor may see and do.

  @behavior-account.authenticate-session
  Scenario Outline: Authenticate and end an opaque revocable session
    Given <identity_protocol> through <provider_case> presents <claim_case> for <actor_kind>
    And the account policy is <policy_case>
    When the actor performs <protocol_action> for <session_target>
    Then authentication ends as <authentication_outcome>
    And external group or role data ends as <group_outcome>
    And session isolation ends as <session_outcome>
    And opaque session credential material cannot be recovered from stored state
    And replayed, expired, or forged claims expose no session
    And a revoked or ended session no longer authorizes requests

    Examples:
      | identity_protocol | provider_case                | claim_case                              | actor_kind       | policy_case               | protocol_action | session_target       | authentication_outcome            | group_outcome                   | session_outcome                              |
      | browser identity  | configured local provider    | valid bound claims                      | person           | local login permitted     | log in          | a new session        | one opaque revocable session       | no undeclared authority         | the new session alone is active              |
      | OIDC              | conformant configured provider | valid code, state, nonce, issuer, audience, signature, and PKCE | person | federated login permitted | log in | a new session | one opaque revocable session | provider groups are quarantined | the new session alone is active              |
      | OIDC              | conformant configured provider | valid identity-linking claims          | person           | identity linking permitted | link identity  | current principal    | identity linked to the same principal | provider groups are quarantined | current sessions remain bound to one principal |
      | OIDC              | conformant configured provider | valid logout claims                    | person           | federated logout permitted | log out        | one selected session | selected session ended             | no undeclared authority         | another principal and session remain active  |
      | OIDC              | conformant configured provider | forged state                           | person           | federated login permitted | log in          | a new session        | denied without session             | no provider authority admitted  | no session created                            |
      | OIDC              | conformant configured provider | forged nonce                           | person           | federated login permitted | log in          | a new session        | denied without session             | no provider authority admitted  | no session created                            |
      | OIDC              | conformant configured provider | wrong issuer                           | person           | federated login permitted | log in          | a new session        | denied without session             | no provider authority admitted  | no session created                            |
      | OIDC              | conformant configured provider | wrong audience                         | person           | federated login permitted | log in          | a new session        | denied without session             | no provider authority admitted  | no session created                            |
      | OIDC              | conformant configured provider | invalid signature                      | person           | federated login permitted | log in          | a new session        | denied without session             | no provider authority admitted  | no session created                            |
      | enterprise SSO    | conformant configured provider | valid signed assertion with role-bearing groups | person | SSO required | log in | a new session | one opaque revocable session | provider groups are quarantined | the new session alone is active              |
      | enterprise SSO    | conformant configured provider | replayed assertion                     | person           | SSO required              | log in          | a new session        | denied without session             | no provider authority admitted  | no session created                            |
      | enterprise SSO    | conformant configured provider | expired assertion                      | person           | SSO required              | log in          | a new session        | denied without session             | no provider authority admitted  | no session created                            |
      | enterprise SSO    | conformant configured provider | unsigned assertion                     | person           | SSO required              | log in          | a new session        | denied without session             | no provider authority admitted  | no session created                            |
      | enterprise SSO    | conformant configured provider | wrong-audience assertion               | person           | SSO required              | log in          | a new session        | denied without session             | no provider authority admitted  | no session created                            |
      | OIDC              | replacement conformant provider | valid bound claims                    | person           | federated login permitted | log in          | a new session        | the same public session outcome     | provider groups are quarantined | the new session alone is active              |
      | local identity    | configured local provider       | valid current credentials             | person           | SSO required              | log in          | a new session        | denied by the saved SSO policy      | no undeclared authority         | no session created                            |
      | local identity    | configured local provider       | valid current credentials             | service operator | local login permitted     | log out         | one selected session | selected session ended             | no undeclared authority         | another principal and session remain active  |
      | local identity    | configured local provider       | valid current session credential      | person           | session rotation permitted | rotate credential | the current session | one replacement opaque credential | no undeclared authority         | the prior credential is denied and the replacement is active |
      | local identity    | configured local provider       | previously valid claims for a disabled principal | person | local login permitted | use | an existing session | denied without authority | no undeclared authority | every session for the disabled principal is inactive |

  @behavior-account.administer-access
  Scenario Outline: Administer account access without cross-tenant authority
    Given <admin_state> attempts <admin_action> for <resource_scope>
    And the request has <authorization_case>, <subject_case>, and <capacity_case>
    When the access change commits
    Then membership, grant, session, seat, billing view, and audit effects are <transaction_outcome>
    And the response exposes <response_outcome>
    And audit history ends as <audit_outcome>
    And every declared audit event is append-only and retains actor, target, outcome, and exact order
    And disabling or removing a principal immediately ends every active session and protected read or write
    And local and federated principal identities remain collision-free across authorized accounts
    And billing or identity-provider groups grant no undeclared application authority
    And every protected catalog, run, review, Wiki, asset, settings, and billing action independently enforces its effective read and write authority
    And another account's resources remain unavailable

    Examples:
      | admin_state           | admin_action              | resource_scope    | authorization_case                         | subject_case                    | capacity_case               | transaction_outcome                                      | response_outcome                                                    | audit_outcome                              |
      | account admin         | invite member             | selected account  | permitted                                  | active invited person            | seat available               | membership and intended grants applied once              | the authorized account view                                       | exactly one invitation and acceptance history |
      | account admin         | revoke grant              | selected project  | permitted                                  | active member                    | within plan                  | effective access immediately removed                    | the authorized project view                                       | exactly one revocation history             |
      | project member        | assign admin grant        | selected account  | denied                                     | active member                    | within plan                  | absent with no partial side effects                     | a schema-valid denial without protected fields                    | the declared denied-attempt history         |
      | scoped writer         | update allowed field      | selected project  | write permitted and protected reads denied | active writer                    | within plan                  | allowed field changed and audited                       | no protected cost, routing, translation-memory, or status fields  | exactly one allowed-field history           |
      | migration operator    | migrate legacy ownership  | default account   | permitted                                  | representative pre-account data  | within plan                  | every prior object belongs to one valid account and principal | ownership and audit links with no orphan                     | exactly one migration history               |
      | account admin         | grant project permission  | selected project  | permitted                                  | active member                    | within plan                  | effective access granted                                | exact resulting project permissions                               | exactly one grant history                   |
      | account admin         | grant project permission  | selected project  | permitted                                  | disabled member                  | within plan                  | denied with no effective access                         | a schema-valid disabled-subject result                            | the declared denied-attempt history         |
      | account admin         | grant project permission  | foreign project   | permitted for another scope                | active member                    | within plan                  | denied for scope mismatch                               | a schema-valid scope-denial result                                | the declared denied-attempt history         |
      | account admin         | resolve overlapping grants | selected project | one allow and one deny                      | active member                    | within plan                  | deterministic deny wins                                 | exact effective permissions                                      | one resolution history                      |
      | account admin         | accept invitation         | selected account  | permitted                                  | duplicate invitation             | seat available               | duplicate refused without another membership            | exact duplicate-invitation result                                | one original acceptance history             |
      | account admin         | accept invitation         | selected account  | permitted                                  | expired invitation               | seat available               | expired invitation refused                              | exact expiry result                                               | the declared refused-attempt history        |
      | account admin         | accept invitation         | selected account  | permitted                                  | valid invitation                 | seat limit reached           | refused transactionally without membership              | exact seat-capacity and billing view                              | the declared refused-attempt history        |
      | security admin        | revoke selected session   | selected account  | permitted                                  | one live session                 | within plan                  | only the selected session ends                          | safe session metadata without token material                      | exactly one session-revocation history      |
      | security admin        | save SSO policy           | selected account  | permitted                                  | active administrator             | within plan                  | policy version applies to the next login or session      | the authorized security configuration                             | exactly one policy-change history           |
      | project member        | read or save SSO policy   | selected account  | denied                                     | active member                    | within plan                  | no read or mutation effect                              | a schema-valid denial without sensitive configuration             | the declared denied-attempt history         |
      | security admin        | disable principal         | selected account  | permitted                                  | active principal with protected reads, writes, and sessions | within plan | all effective access and sessions immediately revoked | safe disabled-principal metadata without protected resource data | exactly one principal-disable history       |
      | account admin         | add existing identities   | two selected accounts | permitted in both accounts               | one person with local and federated identities | seats available | collision-free memberships reference the intended opaque principal | only the two authorized account memberships             | exactly one membership history per account  |
      | representative permitted and denied actors | read and write catalog, run, review, Wiki, asset, settings, and billing resources | selected and foreign resource scopes | each action uses its exact effective grant | active subjects in the selected account | within plan | only the explicitly permitted effects commit | each class returns its authorized result or a safe denial without protected fields | each class follows its declared success and denial audit policy |
