import type {
  CatalogBenchmarkSeedFinderReadModel,
  CatalogCompletenessBenchmarkPools,
  CatalogConflictReviewReadModel,
  CatalogOpportunityRankingReadModel,
  DashboardDecisionReadModel,
} from "@itotori/db";

export const catalogConflictReviewFixture: CatalogConflictReviewReadModel = {
  rows: [
    {
      reviewId: "catalog-conflict:duplicate-external-id",
      catalogRecordId: "work-duplicate",
      conflictId: "duplicate-external-id",
      candidateIds: ["candidate-prior-1"],
      candidateCatalogIds: ["work-duplicate", "work-other"],
      exactLinkRefs: [
        {
          externalIdId: "external-dlsite-1",
          catalogSource: "dlsite",
          sourceId: "RJ010",
          externalIdKind: "store_product",
          workId: "work-duplicate",
          sourceProvenanceId: "prov-dlsite",
        },
      ],
      fuzzyScores: [],
      sourceIds: [{ catalogSource: "dlsite", sourceId: "RJ010" }],
      provenance: [
        {
          sourceProvenanceId: "prov-dlsite",
          catalogSource: "dlsite",
          sourceId: "RJ010",
          sourceRecordKind: "recorded_fixture",
          payloadHash: null,
          fetchedAt: new Date("2026-06-17T00:00:00.000Z"),
        },
      ],
      privateSourceCount: 0,
      severity: "error",
      status: "open",
      reasonCode: "duplicate_external_id",
      reasonDetail: "DLsite id was observed against multiple catalog identities.",
      conflictOrigin: "fixture_authored",
      conflictKind: "external_id",
      detectedAt: new Date("2026-06-17T00:00:00.000Z"),
      resolution: null,
    },
  ],
};

export const catalogCompletenessFixture: CatalogCompletenessBenchmarkPools = {
  targetLanguage: "en-US",
  pools: {
    mtl_only: [
      {
        workId: "work-mtl",
        canonicalTitle: "MTL Fixture",
        originalLanguage: "ja-JP",
        sourceIds: [{ catalogSource: "egs", sourceId: "egs-mtl" }],
        privateSourceCount: 0,
        statuses: [
          {
            languageStatusId: "status-mtl",
            language: "en-US",
            status: "mtl",
            statusScope: "work",
            platform: null,
            releaseId: null,
            sourceProvenanceId: "prov-egs-mtl",
            source: {
              sourceProvenanceId: "prov-egs-mtl",
              catalogSource: "egs",
              sourceRecordKind: "recorded_fixture",
              sourceId: "egs-mtl",
              sourceVersion: "fixture-2026-06-17",
              fetchedAt: new Date("2026-06-17T00:00:00.000Z"),
              rawContentRedactionClass: "public_metadata",
            },
            privateSourceCount: 0,
            confidence: "medium",
            observedAt: new Date("2026-06-17T00:00:00.000Z"),
            importedAt: new Date("2026-06-17T00:01:00.000Z"),
            parserVersion: "catalog-completeness-fixture.v0.1",
            rawContentRedactionClass: "public_metadata",
          },
        ],
        conflicts: [],
      },
    ],
    fan_partial: [],
    no_english: [],
    unknown: [],
    conflict: [],
  },
  publicReport: {
    schemaVersion: "catalog.completeness_public_report.v0.1",
    targetLanguage: "en-US",
    generatedAt: new Date("2026-06-17T00:02:00.000Z"),
    totalWorkCount: 1,
    conflictCount: 0,
    pools: [
      {
        pool: "mtl_only",
        workCount: 1,
        sourceIds: [{ catalogSource: "egs", sourceId: "egs-mtl" }],
      },
      { pool: "fan_partial", workCount: 0, sourceIds: [] },
      { pool: "no_english", workCount: 0, sourceIds: [] },
      { pool: "unknown", workCount: 0, sourceIds: [] },
      { pool: "conflict", workCount: 0, sourceIds: [] },
    ],
    statuses: [
      { status: "mtl", factCount: 1, sourceIds: [{ catalogSource: "egs", sourceId: "egs-mtl" }] },
    ],
  },
};

export const catalogBenchmarkSeedsFixture: CatalogBenchmarkSeedFinderReadModel = {
  schemaVersion: "catalog.benchmark_seed_finder.v0.1",
  targetLanguage: "en-US",
  generatedAt: new Date("2026-06-17T00:03:00.000Z"),
  rows: [
    {
      workId: "work-seed",
      canonicalTitle: "Benchmark Seed Fixture",
      originalLanguage: "ja-JP",
      sourceIds: [
        {
          catalogSource: "dlsite",
          sourceId: "RJSEED001",
          externalIdKind: "store_product",
        },
      ],
      completenessPool: "no_english",
      translationStatuses: [
        {
          language: "en-US",
          status: "none",
          confidence: "high",
          statusScope: "work",
          platform: null,
        },
      ],
      localOwnership: "owned",
      localEvidenceCount: 1,
      demandBucket: "very_high",
      readiness: {
        adapterId: "adapter-seed",
        identify: "supported",
        inventory: "supported",
        extract: "supported",
        patch: "partial",
        helper: "unknown",
        runtime: "unsupported",
      },
      provenance: [
        {
          catalogSource: "dlsite",
          sourceId: "RJSEED001",
          sourceRecordKind: "recorded_fixture",
          sourceVersion: "fixture-2026-06-17",
          fixtureId: "catalog-benchmark-seeds/dlsite/RJSEED001.json",
          redactionClass: "public_metadata",
        },
      ],
      decision: "seed",
      rank: 1,
      seedRank: 1,
      explanationCodes: ["pool:no_english", "demand_bucket:very_high", "local_ownership:owned"],
    },
  ],
};

export const catalogOpportunitiesFixture: CatalogOpportunityRankingReadModel = {
  schemaVersion: "catalog.opportunity_ranking.v0.1",
  targetLanguage: "en-US",
  generatedAt: new Date("2026-06-27T16:10:00.000Z"),
  weightsVersion: "catalog.opportunity_ranking.weights.v0.1",
  rows: [
    {
      rank: 1,
      workId: "work-opportunity",
      canonicalTitle: "Opportunity API Fixture",
      originalLanguage: "ja-JP",
      sourceIds: [
        {
          catalogSource: "dlsite",
          sourceId: "RJOPPAPI001",
          externalIdKind: "store_product",
        },
      ],
      engineName: "rpg-maker-mv-mz",
      adapterId: "kaifuu.rpg-maker-mv-mz",
      readiness: {
        adapterId: "kaifuu.rpg-maker-mv-mz",
        identify: "supported",
        inventory: "supported",
        extract: "supported",
        patch: "supported",
        helper: "unknown",
        runtime: "partial",
      },
      runtimeEvidenceReadiness: {
        status: "public_and_aggregate",
        publicFixtureEvidenceCount: 1,
        privateLocalAggregateEvidenceCount: 2,
      },
      completenessPool: "no_english",
      translationStatuses: [
        {
          language: "en-US",
          status: "none",
          confidence: "high",
          statusScope: "work",
          platform: null,
        },
      ],
      demandFacts: {
        demandBucket: "very_high",
        dlCount: 61240,
        ratingAverage: 4.72,
        ratingCount: 1880,
        wishlistCount: 12040,
        bestRank: 3,
        workType: "RPG",
      },
      localOwnership: "owned",
      localEvidenceCount: 2,
      marketPrevalence: "public_and_local_aggregate",
      decision: "candidate",
      score: 100,
      factorBreakdown: [
        {
          factor: "translation_completeness",
          weight: 30,
          rawValue: 1,
          weightedScore: 30,
          evidenceRefs: ["catalog-language-status:work-opportunity:en-US:none"],
          explanationCode: "translation_completeness:no_english",
        },
        {
          factor: "local_ownership",
          weight: 8,
          rawValue: 1,
          weightedScore: 8,
          evidenceRefs: ["local_evidence_count:2"],
          explanationCode: "local_ownership:owned",
        },
        {
          factor: "dlsite_demand",
          weight: 20,
          rawValue: 1,
          weightedScore: 20,
          evidenceRefs: ["dlsite:RJOPPAPI001"],
          explanationCode: "dlsite_demand:very_high:rating_high",
        },
        {
          factor: "platform_language_conflict",
          weight: -60,
          rawValue: 0,
          weightedScore: 0,
          evidenceRefs: [],
          explanationCode: "platform_language_conflict:none",
        },
        {
          factor: "market_prevalence",
          weight: 8,
          rawValue: 1,
          weightedScore: 8,
          evidenceRefs: ["source_id_count:1", "local_evidence_count:2"],
          explanationCode: "market_prevalence:public_and_local_aggregate",
        },
        {
          factor: "adapter_readiness",
          weight: 18,
          rawValue: 1,
          weightedScore: 18,
          evidenceRefs: ["kaifuu.rpg-maker-mv-mz"],
          explanationCode: "adapter_readiness:patch_supported",
        },
        {
          factor: "runtime_evidence_readiness",
          weight: 6,
          rawValue: 1,
          weightedScore: 6,
          evidenceRefs: [
            "public_fixture_evidence_count:1",
            "private_local_aggregate_evidence_count:2",
          ],
          explanationCode: "runtime_evidence_readiness:public_and_aggregate",
        },
        {
          factor: "dlsite_work_type",
          weight: 0,
          rawValue: 1,
          weightedScore: 0,
          evidenceRefs: ["work_type:RPG"],
          explanationCode: "dlsite_work_type:rpg",
        },
        {
          factor: "existing_translation_status",
          weight: -20,
          rawValue: 0,
          weightedScore: 0,
          evidenceRefs: ["catalog-language-status:work-opportunity:en-US:none"],
          explanationCode: "existing_translation_status:none",
        },
        {
          factor: "benchmark_usefulness",
          weight: 10,
          rawValue: 1,
          weightedScore: 10,
          evidenceRefs: ["pool:no_english", "demand_bucket:very_high"],
          explanationCode: "benchmark_usefulness:high",
        },
        {
          factor: "unknown_evidence",
          weight: 0,
          rawValue: 0,
          weightedScore: 0,
          evidenceRefs: [],
          explanationCode: "unknown_evidence:none",
        },
      ],
      explanationCodes: [
        "translation_completeness:no_english",
        "local_ownership:owned",
        "dlsite_demand:very_high:rating_high",
        "platform_language_conflict:none",
        "market_prevalence:public_and_local_aggregate",
        "adapter_readiness:patch_supported",
        "runtime_evidence_readiness:public_and_aggregate",
        "dlsite_work_type:rpg",
        "existing_translation_status:none",
        "benchmark_usefulness:high",
        "unknown_evidence:none",
      ],
      provenance: [
        {
          catalogSource: "dlsite",
          sourceId: "RJOPPAPI001",
          sourceRecordKind: "recorded_fixture",
          sourceVersion: "fixture-2026-06-27",
          fixtureId: "catalog-opportunities/fixture.json",
          redactionClass: "public_metadata",
        },
      ],
      demotions: [],
    },
  ],
};

export const dashboardDecisionsFixture: DashboardDecisionReadModel = {
  projectId: "project-1",
  counts: {
    pendingDecisionCount: 3,
    projectFindingDecisionCount: 1,
    localeBranchFindingDecisionCount: 1,
    runtimeValidationDecisionCount: 1,
  },
  pendingDecisions: [
    {
      decisionId: "project_finding:finding-project-1",
      decisionKind: "project_finding",
      projectId: "project-1",
      findingId: "finding-project-1",
      findingKind: "terminology_consistency",
      severity: "P2",
      qualityCategory: "terminology",
      title: "Project terminology review",
      localeBranchId: null,
      targetLocale: null,
      branchStatus: null,
      runtimeRunId: null,
      runtimeStatus: null,
      createdAt: "2026-06-17T00:00:00.000Z",
    },
    {
      decisionId: "locale_branch_finding:finding-locale-1",
      decisionKind: "locale_branch_finding",
      projectId: "project-1",
      findingId: "finding-locale-1",
      findingKind: "protected_span_issue",
      severity: "P1",
      qualityCategory: "protected_content",
      title: "Protected span moved",
      localeBranchId: "locale-1",
      targetLocale: "en-US",
      branchStatus: "active",
      runtimeRunId: null,
      runtimeStatus: null,
      createdAt: "2026-06-17T00:01:00.000Z",
    },
    {
      decisionId: "runtime_validation:finding-runtime-1",
      decisionKind: "runtime_validation",
      projectId: "project-1",
      findingId: "finding-runtime-1",
      findingKind: "text_mismatch",
      severity: "P2",
      qualityCategory: "runtime_validation",
      title: "Runtime validation: text_mismatch",
      localeBranchId: "locale-1",
      targetLocale: "en-US",
      branchStatus: "active",
      runtimeRunId: "runtime-1",
      runtimeStatus: "failed",
      createdAt: "2026-06-17T00:02:00.000Z",
    },
  ],
};
