import { readFileSync } from "node:fs";
import type {
  DashboardDecisionReadModel,
  ProjectCostReport,
  ProjectDashboardStatus,
  RuntimeDashboardStatus,
} from "@itotori/db";
import type {
  BenchmarkReportV02,
  BridgeBundle,
  FindingRecordV02,
  RuntimeVerificationReport,
  TriageEventV02,
} from "@itotori/localization-bridge-schema";
import type { ProjectState, RuntimeIngestResult } from "../src/services/project-workflow.js";

export const costReportFixture: ProjectCostReport = {
  projectId: "project-1",
  currency: "USD",
  runCount: 2,
  billedMicrosUsd: 1200,
  estimatedMicrosUsd: 980,
  zeroRunCount: 0,
  unknownRunCount: 0,
  includesUnknownCost: false,
  totalsByCostKind: [
    {
      costKind: "billed",
      runCount: 1,
      amountMicrosUsd: 1200,
      promptTokens: 12,
      completionTokens: 8,
      totalTokens: 20,
    },
    {
      costKind: "provider_estimate",
      runCount: 1,
      amountMicrosUsd: 980,
      promptTokens: 10,
      completionTokens: 6,
      totalTokens: 16,
    },
    {
      costKind: "local_estimate",
      runCount: 0,
      amountMicrosUsd: 0,
      promptTokens: 0,
      completionTokens: 0,
      totalTokens: 0,
    },
    {
      costKind: "zero",
      runCount: 0,
      amountMicrosUsd: 0,
      promptTokens: 0,
      completionTokens: 0,
      totalTokens: 0,
    },
    {
      costKind: "unknown",
      runCount: 0,
      amountMicrosUsd: 0,
      promptTokens: 0,
      completionTokens: 0,
      totalTokens: 0,
    },
  ],
  recentRuns: [
    {
      providerRunId: "provider-run-1",
      taskKind: "draft_translation",
      status: "succeeded",
      startedAt: "2026-06-17T00:00:00.000Z",
      structuredOutputMode: "json_schema",
      retryCount: 0,
      errorClasses: [],
      providerFamily: "fake",
      endpointFamily: "chat-completions",
      providerName: "itotori-fixture",
      requestedModelId: "itotori-fake-draft-v0",
      actualModelId: "itotori-fake-draft-v0",
      upstreamProvider: null,
      routeSettingsHash: null,
      promptPresetId: "itotori-draft-default-v1",
      promptTemplateVersion: "1.0.0",
      promptHash: "sha256:1111111111111111111111111111111111111111111111111111111111111111",
      fallbackUsed: false,
      fallbackPlan: ["itotori-fake-draft-v0"],
      costKind: "billed",
      amountMicrosUsd: 1200,
      tokenCountSource: "provider_reported",
      promptTokens: 12,
      completionTokens: 8,
      reasoningTokens: null,
      cachedInputTokens: null,
      totalTokens: 20,
      dataHandling: {
        costTier: "local",
        promptLogging: "not_applicable",
        completionLogging: "not_applicable",
        retention: "not_applicable",
        trainingUse: "not_applicable",
        dataCollection: "not_applicable",
        rawCaptureDefault: "disabled",
      },
      accountPrivacy: null,
    },
    {
      providerRunId: "provider-run-2",
      taskKind: "benchmark_qa",
      status: "succeeded",
      startedAt: "2026-06-17T00:01:00.000Z",
      structuredOutputMode: "plain_json",
      retryCount: 1,
      errorClasses: ["provider_timeout_retry"],
      providerFamily: "openrouter",
      endpointFamily: "chat-completions",
      providerName: "openrouter",
      requestedModelId: "itotori-fake-qa-v0",
      actualModelId: "itotori-fake-qa-v1",
      upstreamProvider: "fixture-upstream",
      routeSettingsHash: "sha256:3333333333333333333333333333333333333333333333333333333333333333",
      promptPresetId: "itotori-benchmark-qa-v1",
      promptTemplateVersion: "1.0.0",
      promptHash: "sha256:2222222222222222222222222222222222222222222222222222222222222222",
      fallbackUsed: true,
      fallbackPlan: ["itotori-fake-qa-v0", "itotori-fake-qa-v1"],
      costKind: "provider_estimate",
      amountMicrosUsd: 980,
      tokenCountSource: "estimated",
      promptTokens: 10,
      completionTokens: 6,
      reasoningTokens: null,
      cachedInputTokens: null,
      totalTokens: 16,
      dataHandling: {
        costTier: "paid",
        promptLogging: "unknown",
        completionLogging: "unknown",
        retention: "unknown",
        trainingUse: "unknown",
        dataCollection: "deny",
        rawCaptureDefault: "disabled",
      },
      accountPrivacy: {
        inputOutputLogging: "disabled",
        useOfInputsOutputs: "deny",
        providerDataPolicyFilters: "enabled",
        metadataCollection: "expected",
        euRouting: "unknown",
      },
    },
  ],
};

export const dashboardStatusFixture: ProjectDashboardStatus = {
  projectId: "project-1",
  projectKey: "project-1",
  name: "project-1",
  status: "runtime_ingested",
  sourceLocale: "ja-JP",
  sourceBundleId: "bridge-1",
  sourceBundleHash: "hash-1",
  sourceBundleRevisionId: "revision-1",
  branchCount: 1,
  unitCount: 1,
  findingCount: 3,
  artifactCount: 3,
  latestEventKind: "patch_result_recorded",
  latestEventAt: "2026-06-17T00:00:00.000Z",
  importStatus: {
    bridgeImportId: "bridge-import:project-1:bridge-1:revision-1",
    projectId: "project-1",
    bridgeId: "bridge-1",
    sourceBundleId: "bridge-1",
    sourceBundleHash: "hash-1",
    sourceBundleRevisionId: "revision-1",
    schemaVersion: "0.1.0",
    sourceLocale: "ja-JP",
    importedAt: "2026-06-17T00:00:00.000Z",
    unitCount: 1,
    assetCount: 1,
    sourceRevisionCount: 4,
    validationFailureCount: 0,
    units: { added: 1, updated: 0, removed: 0, unchanged: 0 },
    assets: { added: 1, updated: 0, removed: 0, unchanged: 0 },
    sourceRevisions: { added: 4, existing: 0 },
    futureReferences: {
      catalogWorkId: null,
      localCorpusEntryId: null,
      readinessProfileId: null,
      completenessStatusId: null,
    },
  },
  cost: costReportFixture,
  localeBranches: [
    {
      localeBranchId: "locale-1",
      targetLocale: "en-US",
      status: "active",
      unitCount: 1,
      translatedUnitCount: 1,
      openFindingCount: 1,
      artifactCount: 3,
    },
  ],
};

export const dashboardDecisionsFixture: DashboardDecisionReadModel = {
  projectId: "project-1",
  counts: {
    pendingDecisionCount: 3,
    projectFindingDecisionCount: 1,
    localeBranchFindingDecisionCount: 1,
    runtimeValidationDecisionCount: 1,
  },
  pendingDecisions: [
    {
      decisionId: "project_finding:finding-project-1",
      decisionKind: "project_finding",
      projectId: "project-1",
      findingId: "finding-project-1",
      findingKind: "terminology_consistency",
      severity: "P2",
      qualityCategory: "terminology",
      title: "Project terminology review",
      localeBranchId: null,
      targetLocale: null,
      branchStatus: null,
      runtimeRunId: null,
      runtimeStatus: null,
      createdAt: "2026-06-17T00:00:00.000Z",
    },
    {
      decisionId: "locale_branch_finding:finding-locale-1",
      decisionKind: "locale_branch_finding",
      projectId: "project-1",
      findingId: "finding-locale-1",
      findingKind: "protected_span_issue",
      severity: "P1",
      qualityCategory: "protected_content",
      title: "Protected span moved",
      localeBranchId: "locale-1",
      targetLocale: "en-US",
      branchStatus: "active",
      runtimeRunId: null,
      runtimeStatus: null,
      createdAt: "2026-06-17T00:01:00.000Z",
    },
    {
      decisionId: "runtime_validation:finding-runtime-1",
      decisionKind: "runtime_validation",
      projectId: "project-1",
      findingId: "finding-runtime-1",
      findingKind: "text_mismatch",
      severity: "P2",
      qualityCategory: "runtime_validation",
      title: "Runtime validation: text_mismatch",
      localeBranchId: "locale-1",
      targetLocale: "en-US",
      branchStatus: "active",
      runtimeRunId: "runtime-1",
      runtimeStatus: "failed",
      createdAt: "2026-06-17T00:02:00.000Z",
    },
  ],
};

export const runtimeStatusFixture: RuntimeDashboardStatus = {
  finalStatus: "hello_world_failed",
  runtimeReportId: "runtime-1",
  runtimeStatus: "failed",
  fidelityTier: "layout_probe",
  evidenceTier: null,
  textEventCount: 1,
  frameCaptureCount: 1,
  screenshotArtifactCount: 1,
  recordingArtifactCount: 0,
  validationFindingCount: 1,
};

export const bridgeFixture: BridgeBundle = {
  schemaVersion: "0.1.0",
  bridgeId: "bridge-1",
  sourceBundleHash: "hash-1",
  sourceLocale: "ja-JP",
  extractorName: "kaifuu-fixture",
  extractorVersion: "0.0.0",
  units: [
    {
      bridgeUnitId: "bridge-unit-1",
      sourceUnitKey: "hello.scene.001.line.001",
      occurrenceId: "occurrence-1",
      sourceHash: "source-hash-1",
      sourceLocale: "ja-JP",
      sourceText: "こんにちは、{player}。",
      textSurface: "dialogue",
      protectedSpans: [
        { kind: "placeholder", raw: "{player}", start: 18, end: 26, preserveMode: "exact" },
      ],
      patchRef: {
        assetId: "source.json",
        writeMode: "replace",
        sourceUnitKey: "hello.scene.001.line.001",
      },
    },
  ],
};

export const projectFixture: ProjectState = {
  projectId: "project-1",
  localeBranchId: "locale-1",
  targetLocale: "en-US",
  drafts: { "bridge-unit-1": "Hello, {player}." },
  bridge: bridgeFixture,
};

export const runtimeReportFixture: RuntimeVerificationReport = {
  schemaVersion: "0.1.0",
  runtimeReportId: "runtime-1",
  adapterName: "utsushi-fixture",
  fidelityTier: "layout_probe",
  status: "passed",
  textEvents: [
    {
      runtimeTextEventId: "runtime-text-1",
      bridgeUnitId: "bridge-unit-1",
      text: "Hello, {player}.",
      frame: 1,
    },
  ],
  frameCaptures: [
    {
      frameCaptureId: "frame-1",
      bridgeUnitId: "bridge-unit-1",
      width: 320,
      height: 180,
      nonZeroPixels: 57600,
      artifactPath: "fixture://frame/1",
    },
  ],
  approximations: ["fixture"],
};

export const runtimeIngestResultFixture: RuntimeIngestResult = {
  status: "hello_world_passed",
  bridgeId: "bridge-1",
  localeBranchId: "locale-1",
  patchExportId: undefined,
  patchResultId: "patch-result-1",
  runtimeReportId: "runtime-1",
  dashboard: dashboardStatusFixture,
};

export const decisionEventFixture: TriageEventV02 = {
  eventId: "019ed004-0000-7000-8000-000000000201",
  eventKind: "triage_decision_recorded",
  occurredAt: "2026-06-17T00:00:00.000Z",
  actor: { actorKind: "human", displayName: "Fixture reviewer" },
  subjectRefs: [],
  provenance: [
    {
      provenanceId: "019ed004-0000-7000-8000-000000000202",
      provenanceKind: "human_review",
      noteHash: "sha256:decision-fixture-note",
    },
  ],
  causalLinks: [],
  payload: { optionId: "accept_fixture_decision" },
};

export const findingRecordFixture = readFixture<{ finding: FindingRecordV02 }>(
  "../../../packages/localization-bridge-schema/test/examples/finding-v0.2.json",
).finding;

export const benchmarkReportFixture = readFixture<BenchmarkReportV02>(
  "../../../packages/localization-bridge-schema/test/examples/benchmark-report-v0.2.json",
);

function readFixture<T>(path: string): T {
  return JSON.parse(readFileSync(new URL(path, import.meta.url), "utf8")) as T;
}
