import { readFileSync } from "node:fs";
import type {
  CatalogCompletenessBenchmarkPools,
  CatalogConflictReviewReadModel,
  DashboardDecisionReadModel,
  ProjectCostReport,
  ProjectDashboardStatus,
  RuntimeDashboardStatus,
  TerminologySearchReadModel,
} from "@itotori/db";
import type {
  BenchmarkReportV02,
  BridgeBundle,
  FindingRecordV02,
  RuntimeVerificationReport,
  TriageEventV02,
} from "@itotori/localization-bridge-schema";
import type { ProjectState, RuntimeIngestResult } from "../src/services/project-workflow.js";

export const costReportFixture: ProjectCostReport = {
  projectId: "project-1",
  currency: "USD",
  runCount: 2,
  billedMicrosUsd: 2180,
  zeroRunCount: 0,
  totalsByCostKind: [
    {
      costKind: "billed",
      runCount: 2,
      amountMicrosUsd: 2180,
      promptTokens: 22,
      completionTokens: 14,
      totalTokens: 36,
    },
    {
      costKind: "zero",
      runCount: 0,
      amountMicrosUsd: 0,
      promptTokens: 0,
      completionTokens: 0,
      totalTokens: 0,
    },
  ],
  recentRuns: [
    {
      providerRunId: "provider-run-1",
      taskKind: "draft_translation",
      status: "succeeded",
      startedAt: "2026-06-17T00:00:00.000Z",
      structuredOutputMode: "json_schema",
      retryCount: 0,
      errorClasses: [],
      providerFamily: "fake",
      endpointFamily: "chat-completions",
      providerName: "itotori-fixture",
      requestedModelId: "itotori-fake-draft-v0",
      actualModelId: "itotori-fake-draft-v0",
      upstreamProvider: null,
      routeSettingsHash: null,
      promptPresetId: "itotori-draft-default-v1",
      promptTemplateVersion: "1.0.0",
      promptHash: "sha256:1111111111111111111111111111111111111111111111111111111111111111",
      fallbackUsed: false,
      fallbackPlan: ["itotori-fake-draft-v0"],
      costKind: "billed",
      amountMicrosUsd: 1200,
      tokenCountSource: "provider_reported",
      promptTokens: 12,
      completionTokens: 8,
      reasoningTokens: null,
      cachedInputTokens: null,
      totalTokens: 20,
      dataHandling: {},
      accountPrivacy: null,
    },
    {
      providerRunId: "provider-run-2",
      taskKind: "benchmark_qa",
      status: "succeeded",
      startedAt: "2026-06-17T00:01:00.000Z",
      structuredOutputMode: "plain_json",
      retryCount: 1,
      errorClasses: ["provider_timeout_retry"],
      providerFamily: "openrouter",
      endpointFamily: "chat-completions",
      providerName: "openrouter",
      requestedModelId: "itotori-fake-qa-v0",
      actualModelId: "itotori-fake-qa-v1",
      upstreamProvider: "fixture-upstream",
      routeSettingsHash: "sha256:3333333333333333333333333333333333333333333333333333333333333333",
      promptPresetId: "itotori-benchmark-qa-v1",
      promptTemplateVersion: "1.0.0",
      promptHash: "sha256:2222222222222222222222222222222222222222222222222222222222222222",
      fallbackUsed: true,
      fallbackPlan: ["itotori-fake-qa-v0", "itotori-fake-qa-v1"],
      // ITOTORI-225 — was previously `provider_estimate`; the audited
      // run actually carried a real upstream charge captured from
      // `usage.cost`, so it correctly tags as `billed`.
      costKind: "billed",
      amountMicrosUsd: 980,
      tokenCountSource: "estimated",
      promptTokens: 10,
      completionTokens: 6,
      reasoningTokens: null,
      cachedInputTokens: null,
      totalTokens: 16,
      dataHandling: {},
      accountPrivacy: null,
    },
  ],
  translationMemoryReuse: {
    reuseEventCount: 1,
    appliedCount: 1,
    suggestedCount: 0,
    providerCallAvoidedCount: 1,
    estimatedPromptTokensSaved: 7,
    estimatedCompletionTokensSaved: 5,
    estimatedTotalTokensSaved: 12,
    estimatedCostUsdSaved: null,
    recentEvents: [
      {
        reuseEventId: "tm-reuse-1",
        localeBranchId: "locale-1",
        targetBridgeUnitId: "bridge-unit-repeat",
        memorySegmentId: "tm-memory-1",
        matchKind: "exact",
        matchScore: 1000,
        reuseStatus: "applied",
        sourceHash: "hash:repeat",
        candidateSourceHash: "hash:repeat",
        targetText: "Hello again.",
        providerCallAvoided: true,
        estimatedPromptTokensSaved: 7,
        estimatedCompletionTokensSaved: 5,
        estimatedTotalTokensSaved: 12,
        estimatedCostUsdSaved: null,
        calculation: "deterministic_character_estimate_v1",
        provenance: {
          requestId: "draft:project-1:locale-1:en-US",
          selectedMemorySegmentId: "tm-memory-1",
        },
        createdAt: "2026-06-17T00:02:00.000Z",
      },
    ],
  },
};

export const terminologySearchFixture: TerminologySearchReadModel = {
  query: "Hero",
  normalizedQuery: "hero",
  localeBranchId: "locale-1",
  results: [
    {
      score: 100,
      matchKinds: ["exact_source"],
      term: {
        termId: "term-hero",
        projectId: "project-1",
        localeBranchId: "locale-1",
        sourceTerm: "Hero",
        normalizedSourceTerm: "hero",
        sourceLocale: "ja-JP",
        targetLocale: "en-US",
        preferredTranslation: "Hero",
        normalizedPreferredTranslation: "hero",
        termKind: "character_name",
        partOfSpeech: null,
        status: "active",
        caseSensitive: true,
        notes: null,
        metadata: {},
        createdByUserId: "local-user",
        createdAt: new Date("2026-06-18T00:00:00.000Z"),
        updatedAt: new Date("2026-06-18T00:00:00.000Z"),
        aliases: [
          {
            aliasId: "alias-hero",
            termId: "term-hero",
            aliasText: "勇者",
            normalizedAliasText: "勇者",
            aliasKind: "source_alias",
            locale: "ja-JP",
            metadata: {},
            createdAt: new Date("2026-06-18T00:00:00.000Z"),
          },
        ],
        sourceReferences: [
          {
            sourceRefId: "source-ref-hero",
            termId: "term-hero",
            sourceRevisionId: "source-revision-1",
            bridgeUnitId: "bridge-unit-1",
            sourceProvenanceId: null,
            referenceKind: "source_unit",
            citation: "hello.scene.001.line.001",
            context: "Speaker name",
            metadata: {},
            createdAt: new Date("2026-06-18T00:00:00.000Z"),
          },
        ],
        semanticIndex: {
          semanticIndexId: "semantic-hero",
          termId: "term-hero",
          searchDocument: "Hero\n勇者\nSpeaker name",
          searchTokens: ["hero", "勇者", "speaker", "name"],
          embeddingProvider: "itotori-lexical",
          embeddingModel: "terminology-lexical-token-index-v1",
          embeddingDimension: 0,
          embeddingVector: null,
          contentHash: "sha256:terminology-fixture",
          status: "indexed_lexical",
          metadata: {
            hookKind: "lexical_token_index",
            indexKind: "lexical_token_index",
            semanticReady: false,
            vectorReady: false,
          },
          refreshedAt: new Date("2026-06-18T00:00:00.000Z"),
          createdAt: new Date("2026-06-18T00:00:00.000Z"),
          updatedAt: new Date("2026-06-18T00:00:00.000Z"),
        },
      },
    },
  ],
};

export const dashboardStatusFixture: ProjectDashboardStatus = {
  projectId: "project-1",
  projectKey: "project-1",
  name: "project-1",
  status: "runtime_ingested",
  sourceLocale: "ja-JP",
  sourceBundleId: "bridge-1",
  sourceBundleHash: "hash-1",
  sourceBundleRevisionId: "revision-1",
  branchCount: 2,
  unitCount: 1,
  findingCount: 3,
  artifactCount: 3,
  latestEventKind: "patch_result_recorded",
  latestEventAt: "2026-06-17T00:00:00.000Z",
  selectedLocaleBranchId: "019ed065-0000-7000-8000-000000000110",
  currentStyleGuidePolicyVersionId: "019ed065-0000-7000-8000-000000000120",
  importStatus: {
    bridgeImportId: "bridge-import:project-1:bridge-1:revision-1",
    projectId: "project-1",
    bridgeId: "bridge-1",
    sourceBundleId: "bridge-1",
    sourceBundleHash: "hash-1",
    sourceBundleRevisionId: "revision-1",
    schemaVersion: "0.1.0",
    sourceLocale: "ja-JP",
    importedAt: "2026-06-17T00:00:00.000Z",
    unitCount: 1,
    assetCount: 1,
    sourceRevisionCount: 4,
    validationFailureCount: 0,
    units: { added: 1, updated: 0, removed: 0, unchanged: 0 },
    assets: { added: 1, updated: 0, removed: 0, unchanged: 0 },
    sourceRevisions: { added: 4, existing: 0 },
    futureReferences: {
      catalogWorkId: null,
      localCorpusEntryId: null,
      readinessProfileId: null,
      completenessStatusId: null,
    },
  },
  cost: costReportFixture,
  localeBranches: [
    {
      localeBranchId: "locale-1",
      targetLocale: "en-US",
      status: "active",
      currentStyleGuidePolicyVersionId: null,
      unitCount: 1,
      translatedUnitCount: 1,
      openFindingCount: 1,
      artifactCount: 3,
    },
    {
      localeBranchId: "019ed065-0000-7000-8000-000000000110",
      targetLocale: "fr-FR",
      status: "active",
      currentStyleGuidePolicyVersionId: "019ed065-0000-7000-8000-000000000120",
      unitCount: 1,
      translatedUnitCount: 1,
      openFindingCount: 0,
      artifactCount: 1,
    },
  ],
};

export const catalogConflictReviewFixture: CatalogConflictReviewReadModel = {
  rows: [
    {
      reviewId: "catalog-conflict:duplicate-external-id",
      catalogRecordId: "work-duplicate",
      conflictId: "duplicate-external-id",
      candidateIds: ["candidate-prior-1"],
      candidateCatalogIds: ["work-duplicate", "work-other"],
      exactLinkRefs: [
        {
          externalIdId: "external-dlsite-1",
          catalogSource: "dlsite",
          sourceId: "RJ010",
          externalIdKind: "store_product",
          workId: "work-duplicate",
          sourceProvenanceId: "prov-dlsite",
        },
      ],
      fuzzyScores: [],
      sourceIds: [{ catalogSource: "dlsite", sourceId: "RJ010" }],
      provenance: [
        {
          sourceProvenanceId: "prov-dlsite",
          catalogSource: "dlsite",
          sourceId: "RJ010",
          sourceRecordKind: "recorded_fixture",
          payloadHash: null,
          fetchedAt: new Date("2026-06-17T00:00:00.000Z"),
        },
      ],
      severity: "error",
      status: "open",
      reasonCode: "duplicate_external_id",
      reasonDetail: "DLsite id was observed against multiple catalog identities.",
      conflictKind: "external_id",
      detectedAt: new Date("2026-06-17T00:00:00.000Z"),
      resolution: null,
    },
  ],
};

export const catalogCompletenessFixture: CatalogCompletenessBenchmarkPools = {
  targetLanguage: "en-US",
  pools: {
    mtl_only: [
      {
        workId: "work-mtl",
        canonicalTitle: "MTL Fixture",
        originalLanguage: "ja-JP",
        sourceIds: [{ catalogSource: "egs", sourceId: "egs-mtl" }],
        statuses: [
          {
            languageStatusId: "status-mtl",
            language: "en-US",
            status: "mtl",
            statusScope: "work",
            platform: null,
            releaseId: null,
            sourceProvenanceId: "prov-egs-mtl",
            source: {
              sourceProvenanceId: "prov-egs-mtl",
              catalogSource: "egs",
              sourceRecordKind: "recorded_fixture",
              sourceId: "egs-mtl",
              sourceVersion: "fixture-2026-06-17",
              fetchedAt: new Date("2026-06-17T00:00:00.000Z"),
              rawContentRedactionClass: "public_metadata",
            },
            confidence: "medium",
            observedAt: new Date("2026-06-17T00:00:00.000Z"),
            importedAt: new Date("2026-06-17T00:01:00.000Z"),
            parserVersion: "catalog-completeness-fixture.v0.1",
            rawContentRedactionClass: "public_metadata",
          },
        ],
        conflicts: [],
      },
    ],
    fan_partial: [],
    no_english: [],
    unknown: [],
    conflict: [],
  },
  publicReport: {
    schemaVersion: "catalog.completeness_public_report.v0.1",
    targetLanguage: "en-US",
    generatedAt: new Date("2026-06-17T00:02:00.000Z"),
    totalWorkCount: 1,
    conflictCount: 0,
    pools: [
      {
        pool: "mtl_only",
        workCount: 1,
        sourceIds: [{ catalogSource: "egs", sourceId: "egs-mtl" }],
      },
      { pool: "fan_partial", workCount: 0, sourceIds: [] },
      { pool: "no_english", workCount: 0, sourceIds: [] },
      { pool: "unknown", workCount: 0, sourceIds: [] },
      { pool: "conflict", workCount: 0, sourceIds: [] },
    ],
    statuses: [
      { status: "mtl", factCount: 1, sourceIds: [{ catalogSource: "egs", sourceId: "egs-mtl" }] },
    ],
  },
};

export const dashboardDecisionsFixture: DashboardDecisionReadModel = {
  projectId: "project-1",
  counts: {
    pendingDecisionCount: 3,
    projectFindingDecisionCount: 1,
    localeBranchFindingDecisionCount: 1,
    runtimeValidationDecisionCount: 1,
  },
  pendingDecisions: [
    {
      decisionId: "project_finding:finding-project-1",
      decisionKind: "project_finding",
      projectId: "project-1",
      findingId: "finding-project-1",
      findingKind: "terminology_consistency",
      severity: "P2",
      qualityCategory: "terminology",
      title: "Project terminology review",
      localeBranchId: null,
      targetLocale: null,
      branchStatus: null,
      runtimeRunId: null,
      runtimeStatus: null,
      createdAt: "2026-06-17T00:00:00.000Z",
    },
    {
      decisionId: "locale_branch_finding:finding-locale-1",
      decisionKind: "locale_branch_finding",
      projectId: "project-1",
      findingId: "finding-locale-1",
      findingKind: "protected_span_issue",
      severity: "P1",
      qualityCategory: "protected_content",
      title: "Protected span moved",
      localeBranchId: "locale-1",
      targetLocale: "en-US",
      branchStatus: "active",
      runtimeRunId: null,
      runtimeStatus: null,
      createdAt: "2026-06-17T00:01:00.000Z",
    },
    {
      decisionId: "runtime_validation:finding-runtime-1",
      decisionKind: "runtime_validation",
      projectId: "project-1",
      findingId: "finding-runtime-1",
      findingKind: "text_mismatch",
      severity: "P2",
      qualityCategory: "runtime_validation",
      title: "Runtime validation: text_mismatch",
      localeBranchId: "locale-1",
      targetLocale: "en-US",
      branchStatus: "active",
      runtimeRunId: "runtime-1",
      runtimeStatus: "failed",
      createdAt: "2026-06-17T00:02:00.000Z",
    },
  ],
};

export const runtimeStatusFixture: RuntimeDashboardStatus = {
  finalStatus: "hello_world_failed",
  runtimeRunId: "runtime-1",
  runtimeReportId: "runtime-1",
  runtimeStatus: "failed",
  fidelityTier: "layout_probe",
  evidenceTier: "E2",
  textEventCount: 1,
  frameCaptureCount: 1,
  screenshotArtifactCount: 1,
  recordingArtifactCount: 0,
  validationFindingCount: 1,
  traceEvents: [
    {
      runtimeEventId: "runtime-1:trace-1",
      eventKind: "text_seen",
      bridgeUnitId: "bridge-unit-1",
      sourceUnitKey: "hello.scene.001.line.001",
      draftId: "locale-1:bridge-unit-1",
      runtimeTargetId: "hello.scene.001.line.001",
      evidenceTier: null,
      frame: 12,
      textPreview: "Hello, {player}.",
      artifactIds: ["runtime-1:trace-artifact-1"],
    },
  ],
  findings: [
    {
      findingId: "runtime-1:finding-1",
      findingKind: "text_mismatch",
      severity: "error",
      message: "Observed runtime text did not match the draft text.",
      evidenceTier: "E2",
      bridgeUnitId: "bridge-unit-1",
      sourceUnitKey: "hello.scene.001.line.001",
      artifactId: "runtime-1:trace-artifact-1",
    },
  ],
  artifacts: [
    {
      artifactId: "runtime-1:screenshot-1",
      artifactKind: "screenshot",
      uri: "artifacts/utsushi/runtime/runtime-1/screenshots/screenshot-1.png",
      hash: "sha256:runtime-screenshot",
      mediaType: "image/png",
      byteSize: 2048,
      bridgeUnitId: "bridge-unit-1",
      sourceUnitKey: "hello.scene.001.line.001",
      diagnostic: null,
    },
    {
      artifactId: "runtime-1:trace-artifact-1",
      artifactKind: "trace_log",
      uri: "artifacts/utsushi/runtime/runtime-1/traces/trace-1.json",
      hash: "sha256:runtime-trace",
      mediaType: "application/json",
      byteSize: 512,
      bridgeUnitId: "bridge-unit-1",
      sourceUnitKey: "hello.scene.001.line.001",
      diagnostic: null,
    },
  ],
  approximations: [
    {
      approximationId: "runtime-1:approximation-1",
      approximationTier: "synthetic_fixture",
      scope: "capture",
      description: "Fixture capture approximates a host runtime frame.",
      evidenceTierCeiling: "E2",
      bridgeUnitIds: ["bridge-unit-1"],
    },
  ],
  unsupportedCapabilities: [
    {
      feature: "recording",
      status: "unsupported",
      fidelityTierCeiling: null,
      evidenceTierCeiling: null,
      limitations: ["Fixture adapter does not emit recordings."],
    },
  ],
  limitations: ["No reference-runtime pixel comparison is performed."],
};

export const bridgeFixture: BridgeBundle = {
  schemaVersion: "0.1.0",
  bridgeId: "bridge-1",
  sourceBundleHash: "hash-1",
  sourceLocale: "ja-JP",
  extractorName: "kaifuu-fixture",
  extractorVersion: "0.0.0",
  units: [
    {
      bridgeUnitId: "bridge-unit-1",
      sourceUnitKey: "hello.scene.001.line.001",
      occurrenceId: "occurrence-1",
      sourceHash: "source-hash-1",
      sourceLocale: "ja-JP",
      sourceText: "こんにちは、{player}。",
      textSurface: "dialogue",
      protectedSpans: [
        { kind: "placeholder", raw: "{player}", start: 18, end: 26, preserveMode: "exact" },
      ],
      patchRef: {
        assetId: "source.json",
        writeMode: "replace",
        sourceUnitKey: "hello.scene.001.line.001",
      },
    },
  ],
};

export const projectFixture: ProjectState = {
  projectId: "project-1",
  localeBranchId: "locale-1",
  targetLocale: "en-US",
  drafts: { "bridge-unit-1": "Hello, {player}." },
  bridge: bridgeFixture,
};

export const nonJapaneseTargetProjectFixture: ProjectState = {
  projectId: "project-de-en",
  localeBranchId: "locale-de-en-us",
  targetLocale: "en-US",
  drafts: { "bridge-unit-de": "Good day, {player}." },
  bridge: {
    ...bridgeFixture,
    bridgeId: "bridge-de",
    sourceBundleHash: "hash-de",
    sourceLocale: "de-DE",
    units: [
      {
        ...bridgeFixture.units[0]!,
        bridgeUnitId: "bridge-unit-de",
        sourceUnitKey: "tag.scene.001.line.001",
        occurrenceId: "occurrence-de-1",
        sourceHash: "source-hash-de-1",
        sourceLocale: "de-DE",
        sourceText: "Guten Tag, {player}.",
        protectedSpans: [
          { kind: "placeholder", raw: "{player}", start: 11, end: 19, preserveMode: "exact" },
        ],
        patchRef: {
          assetId: "source-de.json",
          writeMode: "replace",
          sourceUnitKey: "tag.scene.001.line.001",
        },
      },
    ],
  },
};

export const runtimeReportFixture: RuntimeVerificationReport = {
  schemaVersion: "0.1.0",
  runtimeReportId: "runtime-1",
  adapterName: "utsushi-fixture",
  fidelityTier: "layout_probe",
  status: "passed",
  textEvents: [
    {
      runtimeTextEventId: "runtime-text-1",
      bridgeUnitId: "bridge-unit-1",
      text: "Hello, {player}.",
      frame: 1,
    },
  ],
  frameCaptures: [
    {
      frameCaptureId: "frame-1",
      bridgeUnitId: "bridge-unit-1",
      width: 320,
      height: 180,
      nonZeroPixels: 57600,
      artifactPath: "fixture://frame/1",
    },
  ],
  approximations: ["fixture"],
};

export const runtimeIngestResultFixture: RuntimeIngestResult = {
  status: "hello_world_passed",
  bridgeId: "bridge-1",
  localeBranchId: "locale-1",
  patchExportId: undefined,
  patchResultId: "patch-result-1",
  runtimeReportId: "runtime-1",
  dashboard: dashboardStatusFixture,
};

export const decisionEventFixture: TriageEventV02 = {
  eventId: "019ed004-0000-7000-8000-000000000201",
  eventKind: "triage_decision_recorded",
  occurredAt: "2026-06-17T00:00:00.000Z",
  actor: { actorKind: "human", displayName: "Fixture reviewer" },
  subjectRefs: [],
  provenance: [
    {
      provenanceId: "019ed004-0000-7000-8000-000000000202",
      provenanceKind: "human_review",
      noteHash: "sha256:decision-fixture-note",
    },
  ],
  causalLinks: [],
  payload: { optionId: "accept_fixture_decision" },
};

export const findingRecordFixture = readFixture<{ finding: FindingRecordV02 }>(
  "../../../packages/localization-bridge-schema/test/examples/finding-v0.2.json",
).finding;

export const benchmarkReportFixture = readFixture<BenchmarkReportV02>(
  "../../../packages/localization-bridge-schema/test/examples/benchmark-report-v0.2.json",
);

function readFixture<T>(path: string): T {
  return JSON.parse(readFileSync(new URL(path, import.meta.url), "utf8")) as T;
}
