// ITOTORI-149 — Character-relationship agent recorded-provider replay test
// (end-to-end gap #1 deferred by ITOTORI-014).
//
// `generateCharacterRelationships` is driven by a SEALED provider transcript
// committed at
// `apps/itotori/test/fixtures/character-relationship-recorded-bundle.json`.
// The replay proves the agent exercises the same parse → validate →
// project-to-record path as a real provider call WITHOUT touching the
// network, then asserts the bios+relationships pack matches the committed
// snapshot at
// `apps/itotori/test/fixtures/character-relationship-pack-snapshot.json`
// BYTE-FOR-BYTE (deterministic).
//
// Determinism surface — what is fixed and why:
//   • `schemaVersion` of the recorded bundle is locked to
//     RECORDED_PROVIDER_BUNDLE_SCHEMA_VERSION (v3); pre-v3 bundles fail at
//     `RecordedModelProvider` construction with a typed
//     RecordedBundleSchemaMismatchError.
//   • Each `RecordedProviderResponse` carries the required `tokenUsage`,
//     `cost`, `routingPosture`, and `usageResponseJson` per ITOTORI-228 /
//     230 / 232 / genaudit2-01 — no char/4 estimate laundering.
//   • The fixed `bundleKey` override (`"char-rel-recorded-bundle-001-key"`)
//     means the bundle's lookup key is independent of the input's prompt
//     hash (which would otherwise drift on any prompt-template change). The
//     test would still find the response after a template bump because the
//     key is pinned here, not derived — this is the canonical pattern for a
//     "sealed" replay.
//   • `now` (the `fixedNow` test seam on CharacterRelationshipInput) pins
//     `generatedAt`, and `promptHash` is computed from the deterministic
//     rendered prompt.
//
// What is NOT in the snapshot and why:
//   • `id` on bios + relationships is generated by `createUuid7` and is
//     therefore random (and not stable across runs). The test strips `id`
//     before comparing to the snapshot; this is the ONLY non-deterministic
//     field on the pack. (ProviderRunRecord is excluded from the pack
//     snapshot entirely — its `runId` is also random via
//     `createProviderRunId`.)

import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import { estimateTokens } from "../src/batch-planner/token-estimator.js";
import {
  buildPrompt,
  generateCharacterRelationships,
  promptHash,
  type BridgeUnitForCharacter,
  type CharacterBio,
  type CharacterRelationship,
  type CharacterRelationshipInput,
  type CharacterRelationshipModelProfile,
  type CuratedCharacterRef,
} from "../src/agents/character-relationship/index.js";
import { ZERO_COST } from "../src/providers/cost.js";
import {
  RECORDED_PROVIDER_BUNDLE_SCHEMA_VERSION,
  RecordedModelProvider,
  type RecordedProviderBundle,
} from "../src/providers/recorded.js";
import type { GlossaryRef } from "../src/batch-planner/shapes.js";

const here = dirname(fileURLToPath(import.meta.url));

// Fixed bundle key — independent of prompt hash so the bundle stays the
// canonical sealed transcript even if the prompt template bumps later.
const RECORDED_BUNDLE_KEY = "char-rel-recorded-bundle-001-key";

const FIXED_NOW = new Date("2026-06-23T12:00:00.000Z");
const fixedNow = (): Date => FIXED_NOW;

function modelProfile(): CharacterRelationshipModelProfile {
  return {
    providerFamily: "fake",
    modelId: "itotori-fake-character-relationship-v0",
    // ITOTORI-220 — required (modelId, providerId) pair.
    providerId: "fake-fixture",
    contextWindowTokens: 16000,
    maxOutputTokens: 1024,
  };
}

function unitsFixture(): BridgeUnitForCharacter[] {
  return [
    {
      bridgeUnitId: "019ed018-0000-7000-8000-000000000a01",
      sourceUnitKey: "scene.001.line.001",
      sourceText: "勇者は王様に挨拶した。",
      sourceHash: "hash-a-1",
      speaker: "勇者",
      addressees: ["王様"],
    },
    {
      bridgeUnitId: "019ed018-0000-7000-8000-000000000a02",
      sourceUnitKey: "scene.001.line.002",
      sourceText: "王様はうなずいた。",
      sourceHash: "hash-a-2",
      speaker: "王様",
    },
    {
      bridgeUnitId: "019ed018-0000-7000-8000-000000000a03",
      sourceUnitKey: "scene.001.line.003",
      sourceText: "勇者と王女は古くからの友人だ。",
      sourceHash: "hash-a-3",
      speaker: "narrator",
      addressees: ["勇者", "王女"],
    },
  ];
}

function curatedFixture(): CuratedCharacterRef[] {
  return [
    { characterId: "勇者", displayName: "勇者ハル" },
    { characterId: "王様", displayName: "王" },
    { characterId: "王女", displayName: "王女ミラ" },
  ];
}

function glossaryFixture(): GlossaryRef[] {
  return [
    {
      termId: "term-yusha",
      termKey: "yusha",
      preferredSourceForm: "勇者",
      preferredTargetForm: "hero",
      hitBridgeUnitIds: ["019ed018-0000-7000-8000-000000000a01"],
    },
  ];
}

function inputFixture(): CharacterRelationshipInput {
  return {
    projectId: "019ed018-0000-7000-8000-000000000001",
    localeBranchId: "019ed018-0000-7000-8000-000000000002",
    sourceRevisionId: "019ed018-0000-7000-8000-000000000003",
    sourceLocale: "ja-JP",
    units: unitsFixture(),
    curatedCharacters: curatedFixture(),
    glossaryExcerpt: glossaryFixture(),
    modelProfile: modelProfile(),
    now: fixedNow,
  };
}

/**
 * Build the in-memory bundle for the test by loading the committed bundle
 * JSON and overriding the bundle's `responses` map with a single response
 * keyed by the pinned `RECORDED_BUNDLE_KEY`. The committed file pins the
 * sealed response content + captured provider identity + the v3 schema
 * envelope (cost, routing posture, usage block); this wrapper only re-keys
 * the response to the test's fixed key so the replay is hermetic.
 */
function loadSealedBundle(): RecordedProviderBundle {
  const committed = JSON.parse(
    readFileSync(join(here, "fixtures/character-relationship-recorded-bundle.json"), "utf8"),
  ) as RecordedProviderBundle;
  // The committed file carries one response under `RECORDED_BUNDLE_KEY`;
  // re-key so a stale `bundleKey` derivation on the recorded provider can
  // never accidentally match this test.
  const sealedResponse = committed.responses[RECORDED_BUNDLE_KEY];
  if (!sealedResponse) {
    throw new Error(`sealed bundle missing required response under key '${RECORDED_BUNDLE_KEY}'`);
  }
  // The committed bundle IS the sealed transcript — return it verbatim so
  // the test fails loud on any committed-field drift (schemaVersion bump,
  // missing cost/routingPosture/usageResponseJson, schema mismatch).
  return {
    ...committed,
    responses: { [RECORDED_BUNDLE_KEY]: sealedResponse },
  };
}

type SnapshotPack = {
  bios: Array<Omit<CharacterBio, "id" | "promptHash"> & { promptHash: string }>;
  relationships: Array<Omit<CharacterRelationship, "id" | "promptHash"> & { promptHash: string }>;
};

function loadPackSnapshot(): SnapshotPack {
  const raw = JSON.parse(
    readFileSync(join(here, "fixtures/character-relationship-pack-snapshot.json"), "utf8"),
  ) as { bios: SnapshotPack["bios"]; relationships: SnapshotPack["relationships"] };
  return raw;
}

/**
 * Canonicalise the agent's pack output for byte-for-byte snapshot
 * comparison. Strips the random `id` field (UUID7 is non-deterministic).
 * `providerRun` is dropped because `runId` is also random.
 */
function canonicalisePack(pack: {
  bios: CharacterBio[];
  relationships: CharacterRelationship[];
  // providerRun deliberately not part of the snapshot.
}): {
  bios: Array<Omit<CharacterBio, "id">>;
  relationships: Array<Omit<CharacterRelationship, "id">>;
} {
  return {
    bios: pack.bios.map(({ id: _id, ...rest }) => rest),
    relationships: pack.relationships.map(({ id: _id, ...rest }) => rest),
  };
}

describe("character-relationship-agent-recorded (ITOTORI-149)", () => {
  it("replays the sealed recorded bundle and matches the committed snapshot byte-for-byte", async () => {
    const input = inputFixture();
    const bundle = loadSealedBundle();

    // Pre-flight: the bundle's schemaVersion must be the current
    // RECORDED_PROVIDER_BUNDLE_SCHEMA_VERSION — otherwise construction
    // would fail and the byte-for-byte contract would be untestable.
    expect(bundle.schemaVersion).toBe(RECORDED_PROVIDER_BUNDLE_SCHEMA_VERSION);

    const provider = new RecordedModelProvider({
      bundle,
      // Pinned key — see header for why we override the default key.
      bundleKey: () => RECORDED_BUNDLE_KEY,
    });

    const output = await generateCharacterRelationships(input, { provider });

    // Sanity gates: the parse + validate path produced a Fresh pack with
    // non-empty citations and the recorded token usage flowed through.
    expect(output.bios).toHaveLength(3);
    expect(output.relationships).toHaveLength(2);
    for (const bio of output.bios) {
      expect(bio.status).toBe("Fresh");
      expect(bio.citedUnitIds.length).toBeGreaterThan(0);
      expect(bio.citedUnitHashes.length).toBe(bio.citedUnitIds.length);
    }
    for (const rel of output.relationships) {
      expect(rel.status).toBe("Fresh");
      expect(rel.citedUnitIds.length).toBeGreaterThan(0);
      expect(rel.citedUnitHashes.length).toBe(rel.citedUnitIds.length);
    }
    expect(output.providerRun.tokenUsage.completionTokens).toBe(384);
    expect(output.providerRun.cost).toEqual(ZERO_COST);

    // Deterministic metadata: prompt hash is computed from the rendered
    // prompt (independent of the recorded bundle), and input token estimate
    // is computed from the same prompt text. The agent stores `promptHash`
    // on bios/relationships as the RAW sha256 hex (no `sha256:` prefix);
    // the prompt-pinning `request.prompt.promptHash` is the prefixed form.
    const rendered = buildPrompt(input);
    const expectedRawPromptHash = promptHash(rendered);
    const expectedPromptHashPrefixed = `sha256:${expectedRawPromptHash}`;
    const expectedInputTokenEstimate = estimateTokens(
      `${rendered.systemText}\n${rendered.userText}`,
    );

    for (const bio of output.bios) {
      expect(bio.promptHash).toBe(expectedRawPromptHash);
      expect(bio.inputTokenEstimate).toBe(expectedInputTokenEstimate);
      expect(bio.generatedAt).toBe(FIXED_NOW.toISOString());
    }
    for (const rel of output.relationships) {
      expect(rel.promptHash).toBe(expectedRawPromptHash);
      expect(rel.generatedAt).toBe(FIXED_NOW.toISOString());
    }
    expect(output.providerRun.prompt.promptHash).toBe(expectedPromptHashPrefixed);

    // Inject the computed values into the snapshot so the byte-for-byte
    // comparison sees matching promptHash + inputTokenEstimate fields.
    const snapshot = loadPackSnapshot();
    for (const bio of snapshot.bios) {
      bio.promptHash = expectedRawPromptHash;
      bio.inputTokenEstimate = expectedInputTokenEstimate;
    }
    for (const rel of snapshot.relationships) {
      rel.promptHash = expectedRawPromptHash;
    }

    // Byte-for-byte comparison against the committed snapshot — the
    // random `id` fields are stripped; everything else MUST match.
    const canonical = canonicalisePack(output);

    expect(JSON.stringify(canonical.bios, null, 2)).toBe(JSON.stringify(snapshot.bios, null, 2));
    expect(JSON.stringify(canonical.relationships, null, 2)).toBe(
      JSON.stringify(snapshot.relationships, null, 2),
    );
  });

  it("two replays of the sealed bundle against the same input produce byte-equal packs", async () => {
    const input = inputFixture();
    const bundle = loadSealedBundle();
    const provider = new RecordedModelProvider({
      bundle,
      bundleKey: () => RECORDED_BUNDLE_KEY,
    });

    const a = await generateCharacterRelationships(input, { provider });
    const b = await generateCharacterRelationships(input, { provider });

    // The agent is a pure parse/validate/project pipeline over the
    // provider's content; same input + same bundle content → same pack
    // structure. `id` is the only non-deterministic field; canonicalise it
    // out before the byte-equal assertion.
    const aCanonical = canonicalisePack(a);
    const bCanonical = canonicalisePack(b);
    expect(JSON.stringify(aCanonical.bios, null, 2)).toBe(JSON.stringify(bCanonical.bios, null, 2));
    expect(JSON.stringify(aCanonical.relationships, null, 2)).toBe(
      JSON.stringify(bCanonical.relationships, null, 2),
    );
  });
});
