import type { TerminalContractName } from "../src/contracts/index.js";
import {
  acceptedOutputExample,
  contextScopeExample,
  contextSnapshotExample,
  defectBundleExample,
  draftBatchExample,
  glossaryFactExample,
  localizedRenderingExample,
  localizationSnapshotExample,
  reviewVerdictExample,
  runModeExample,
  wikiObjectExample,
} from "./contract-fixtures-core.js";
import {
  callResultExample,
  callSpecExample,
  conversationEventExample,
  memoExample,
  memoKeyExample,
  memoValueExample,
} from "./contract-fixtures-calls.js";
import {
  backTranslateResultExample,
  decodeGetCharacterOccurrencesResultExample,
  decodeGetNeighborsResultExample,
  decodeGetRouteGraphResultExample,
  decodeGetUnitsResultExample,
  glossaryLookupResultExample,
  outputsGetAcceptedResultExample,
  referencesSearchResultExample,
  renderAndOcrResultExample,
  webSearchResultExample,
} from "./contract-fixtures-tools.js";

export const terminalContractExamples = {
  runMode: runModeExample,
  contextScope: contextScopeExample,
  callSpec: callSpecExample,
  callResult: callResultExample,
  physicalStepMemoKey: memoKeyExample,
  physicalStepMemoValue: memoValueExample,
  physicalStepMemo: memoExample,
  contextSnapshot: contextSnapshotExample,
  localizationSnapshot: localizationSnapshotExample,
  conversationEvent: conversationEventExample,
  fact: glossaryFactExample,
  wikiObject: wikiObjectExample,
  localizedRendering: localizedRenderingExample,
  draftBatch: draftBatchExample,
  reviewVerdict: reviewVerdictExample,
  defectBundle: defectBundleExample,
  acceptedOutput: acceptedOutputExample,
  decodeGetUnitsResult: decodeGetUnitsResultExample,
  decodeGetNeighborsResult: decodeGetNeighborsResultExample,
  decodeGetRouteGraphResult: decodeGetRouteGraphResultExample,
  decodeGetCharacterOccurrencesResult: decodeGetCharacterOccurrencesResultExample,
  glossaryLookupResult: glossaryLookupResultExample,
  outputsGetAcceptedResult: outputsGetAcceptedResultExample,
  referencesSearchResult: referencesSearchResultExample,
  webSearchResult: webSearchResultExample,
  backTranslateResult: backTranslateResultExample,
  renderAndOcrResult: renderAndOcrResultExample,
} as const satisfies Readonly<Record<TerminalContractName, unknown>>;
